### ISSUE TITLE
Fullscreen shortcut

### ISSUE THREAD

**Issue by montogeek** [zeit/hyperterm#1]
Fullscreen mode would be great :)

Edit: With shortcut support

**Comment by oskarkrawczyk** [comment]
<img width="318" alt="screen shot 2016-07-02 at 08 47 32" src="https://cloud.githubusercontent.com/assets/34213/16538894/a3d23474-4031-11e6-8d0a-af6f7be60b55.png">

Green circle = fullscreen.

Although, having a shortcut would be cool.

**Comment by dariocravero** [comment]
Also, double click on the header should probably do that too

**Comment by dariocravero** [comment]
@oskarkrawczyk sorry I meant that behaviour :)

**Comment by montogeek** [comment]
@oskarkrawczyk I completely miss the button, since is a _console_ app I expected a shortcut

**Comment by rauchg** [comment]
Done!

**Comment by mattapperson** [comment]
@rauchg I would like to request that this be re-opened to also add support for full screen show/hide as iTerm2 has

**Comment by nathanielescribano** [comment]
By full screen show/hide, do you mean the non native full screen support that was introduced around macos 10.7? if so, i would like the same.

**Comment by rauchg** [comment]
Can you create a new issue please @mattapperson? I don't follow

**Comment by mattapperson** [comment]
@nathanielescribano @rauchg opened here https://github.com/zeit/hyperterm/issues/397

**Comment by thomasballinger** [comment]
@nathanielescribano do you mean the ctrl-
