### ISSUE TITLE
Take rgba values in css. 

### ISSUE THREAD

**Issue by Loonz206** [zeit/hyperterm#103]
Would be awesome to get rgba as a color value. Could this be considered?

**Comment by marcbachmann** [comment]
I have no idea why there's `hex` written in parentheses. rgba is working 😆 
![image](https://cloud.githubusercontent.com/assets/431376/16887759/36b1165c-4adc-11e6-831e-052da2adf946.png)

**Comment by Loonz206** [comment]
What about combos? Like adding opacity?

**Comment by huytd** [comment]
@Loonz206: In @marcbachmann's example you can see it also has opacity. I also tried and it worked well.

I think the author just forgot to mention it.

**Comment by Loonz206** [comment]
I can't for the life of me make my terminal transparent...

**Comment by marcbachmann** [comment]
You mean the whole terminal. Yes that isn't supported yet because electron doesn't support that yet. There's a separate issue for that: https://github.com/zeit/hyperterm/issues/87

**Comment by Loonz206** [comment]
Cool. Then I will watch #87 this can be considered closed.
