### ISSUE TITLE
Switching tabs with `CMD+Shift+[` `CMD+Shift+]`

### ISSUE THREAD

**Issue by oskarkrawczyk** [zeit/hyperterm#11]
This is funny, I had a conversation about switching tabs via arrows vs `[]` with many people, the split is right there in the middle.

I'd definitely love to see `CMD+Shift+[` and `CMD+Shift+]` working in Hyperterm.

**Comment by rauchg** [comment]
Done. Good idea. Having _all of the shortcuts_ work out of the box is a big priority. Nothing worse than fighting a new tool :D
