### ISSUE TITLE
Extra `%` signs appearing after commands

### ISSUE THREAD

**Issue by satya164** [zeit/hyperterm#12]
Shell: zsh

Here is what I see on the Terminal,

![screen shot 2016-07-02 at 5 45 41 pm](https://cloud.githubusercontent.com/assets/1174278/16540288/ebc2ce60-407c-11e6-9b7e-84ee4c7fca03.png)

**Comment by zouhir** [comment]
May I ask what setup is this (oh-my-zsh or your own dotfiles & picked plugins)? [Paul Irish's setup](https://twitter.com/paul_irish/status/749077251539341313) looks fine

**Comment by satya164** [comment]
@zouhir here you go - https://github.com/satya164/dotfiles/blob/master/.zshrc

**Comment by oskarkrawczyk** [comment]
Using ohmyzsh and also getting this, although only on launch:
 
<img width="368" alt="screen shot 2016-07-03 at 12 14 44" src="https://cloud.githubusercontent.com/assets/34213/16544926/c3217dda-4117-11e6-9f1f-82eca35c49df.png">

iTerm:

<img width="409" alt="screen shot 2016-07-03 at 12 17 06" src="https://cloud.githubusercontent.com/assets/34213/16544931/17e2e282-4118-11e6-9346-6d99635b5887.png">

**Comment by OlliV** [comment]
Normally zsh prints extra '%' looking like that if the previous command didn't print '\n' as the last character.

**Comment by rauchg** [comment]
This might be fixed by `0.2.0`. Let me know if it still happens when you upgrade.

**Comment by satya164** [comment]
Seems to be fixed in the latest version.
