### ISSUE TITLE
Help > About throws an exception

### ISSUE THREAD

**Issue by Tyriar** [zeit/hyperterm#120]
Ubuntu 16.04

![image](https://cloud.githubusercontent.com/assets/2193314/16889574/49db95ee-4a9c-11e6-8db4-e782e6eca4d4.png)

**Comment by flybayer** [comment]
@Tyriar can you see if this is fixed in the current master branch?

**Comment by Tyriar** [comment]
@flybayer I'm not using hyperterm atm, I doubt it repros since you now ship a .deb
