### ISSUE TITLE
Allow to disable sounds in configuration file

### ISSUE THREAD

**Issue by vslinko** [zeit/hyperterm#125]
"Ding" sound for example.

**Comment by sheerun** [comment]
Could we please change default sound indication to something else? I do lot of Vim and I'm used to press "Esc" multiple times just to be sure, and every time it makes ding.. A little flask of titlebar would be far more pleasurable, but sufficient indication.

**Comment by gerchicov-bp** [comment]
@albinekb it doesn't work in both windows and osx
