### ISSUE TITLE
Editor width doesn't match terminal width

### ISSUE THREAD

**Issue by jeherve** [zeit/hyperterm#13]
- Shell: zsh
- Editing files with `vim` or `nano`

### Steps to reproduce

1. Open Hyperterm
2. Make the app window a bit bigger with your mouse
3. Open a file with `vim` or `nano`
4. Long lines get wrapped before the end of the terminal window.

![screen shot 2016-07-02 at 3 04 31 pm](https://cloud.githubusercontent.com/assets/426388/16540472/4f166cb8-4066-11e6-92bb-45f3f2fa8d76.png)

**Comment by bastilian** [comment]
I can reproduce this here as well. It seems that when opening a new tab there is a default, which gets adjusted on resize. The rows have full width when the window triggers a resize.

**Comment by montogeek** [comment]
Is on the TODO `Listen on resize event coming from the pty.`
