### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by Rydgel** [zeit/hyperterm#131]
Strange issues with "special characters".
For example typing, `é` displays `Ã©` in the terminal.
It makes it totally unusable. Is there some configuration I'm missing?

        HyperTerm 0.4.5
        Electron 1.2.5
        darwin x64 15.5.0

**Comment by lee-dohm** [comment]
Following the instructions in [a StackOverflow answer](http://stackoverflow.com/a/8161863/1954), I was able to resolve this by adding the following to my shell profile:

```shell
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

It would be nice still to be able to configure the terminal directly.

**Comment by nfcampos** [comment]
doing that didn't change anything for me

**Comment by YogaPan** [comment]
+1 For this encoding issues.
I can't type traditional Chinese in hyperTerm.
It always turn into some character like "ã¨Ë".

Mac Os X 10.11.5
HyperTerm 0.5.0

**Comment by Rydgel** [comment]
0.6.0 fixes that for me. What about you guys?

**Comment by nfcampos** [comment]
@Rydgel for me as well, now the only characters that are not corrrectly shown are emojis, which are shown like this `�`

**Comment by Dremora** [comment]
I'm on 0.6.0 but Unicode still doesn't work. Typing a Unicode character results in 2 tabs, displaying (e.g. using `ls`) represents each character as `?`.
`zsh 5.2`.

**Comment by staltz** [comment]
Just reporting my issues as well. Funky encoding wizardry is going on that affects not just look and feel, but also actual execution of commands.

Using hyperterm 0.6.0, when I run Jekyll (this happened to 2 different Jekyll projects I have) on Hyperterm:
```
>  raulmariano   jekyll serve                                       
Configuration file: /Users/staltz/oss/raulmariano/_config.yml
            Source: /Users/staltz/oss/raulmariano
       Destination: /Users/staltz/oss/raulmariano/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.1.6 | Error:  "\xE6" on US-ASCII
```

And then when I run it in another terminal:
```
>  raulmariano   jekyll serve
Configuration file: /Users/staltz/oss/raulmariano/_config.yml
            Source: /Users/staltz/oss/raulmariano
       Destination: /Users/staltz/oss/raulmariano/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 1.568 seconds.
 Auto-regeneration: enabled for '/Users/staltz/oss/raulmariano'
Configuration file: /Users/staltz/oss/raulmariano/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

**Comment by albinekb** [comment]
This should be fixed with the addition of `<meta>` https://github.com/zeit/hyperterm/commit/9c50fd5148443927496290811cc356a11f939a1a, which is in the latest release `0.7.1`.

If you're still having issues, please reopen this and we'll investigate 👼

**Comment by jarvan4dev** [comment]
hi, Guys, Why I can't write  Chinese in hterm? just like this "我是一只小鸭子，咿呀咿呀哟"

**Comment by brikou** [comment]
I just made a fresh install and I face encoding trouble too FE "Vidéos" is displayed "Vid??os".

![image](https://cloud.githubusercontent.com/assets/383212/24895476/e1e0bcd4-1e90-11e7-9c9d-61b9e9958ff2.png)

```sh
hyper -v
Hyper version 1.3.1
```

I added `LC_ALL: 'fr_FR.UTF-8'` to env definition and it now work.

@albinekb I can't reopen the issue, but feel free to do for me... Anyway thank for this great app !

**Comment by sundaycrafts** [comment]
I have a same issue. Not fixed for my machine (MacOS sierra in Japanese).

<img width="832" alt="screen shot 2017-05-02 at 8 30 01" src="https://cloud.githubusercontent.com/assets/4732821/25598745/ad5bb7a2-2f11-11e7-87a4-27fb001833bd.png">

**Comment by aqellez** [comment]
Russian (... ubuntu 16.04
![image](https://user-images.githubusercontent.com/7167113/27516857-f0fc3a2c-59eb-11e7-9851-b2daa6f06a35.png)
