### ISSUE TITLE
Can't see current letter cursor is over

### ISSUE THREAD

**Issue by krishnamannem** [zeit/hyperterm#148]
Here is iterm vs hyperterm

![screen shot 2016-07-16 at 12 01 06 am](https://cloud.githubusercontent.com/assets/9054726/16892654/6d406d2e-4ae8-11e6-990d-82da2c2d0086.png)
![screen shot 2016-07-16 at 12 00 59 am](https://cloud.githubusercontent.com/assets/9054726/16892655/70e40d3c-4ae8-11e6-80a3-9a81729c5912.png)
 
It would be nice to be able to see the letter the cursor is currently covering.

**Comment by montogeek** [comment]
In the works on https://github.com/zeit/hyperterm/pull/76

**Comment by albinekb** [comment]
#76 is merged, which let's you set opacity for the cursor using the [`cursorColor` option](https://github.com/zeit/hyperterm/blob/master/app/config-default.js#L10)

**Comment by lordgiotto** [comment]
Maybe consider https://github.com/alvaropinot/hyperterm-cursor to be added to the core?

IMHO making unreadable the letter under the cursor by default is an UX issue :)
