### ISSUE TITLE
Hide OSX close/minimize/maximize button area when fullscreen

### ISSUE THREAD

**Issue by kaicataldo** [zeit/hyperterm#151]
When made fullscreen, the OSX buttons on the top left are hidden, but the area where they were remains. It would look a look nicer if that area wasn't there in fullscreen mode. Looks like the first tab always has `margin-left` property regardless.

Examples:

Current:
<img width="721" alt="screen shot 2016-07-16 at 12 55 12 am" src="https://cloud.githubusercontent.com/assets/7041728/16892858/3629797c-4af0-11e6-9a62-64fb85dbc6b5.png">

Suggested change:
<img width="721" alt="screen shot 2016-07-16 at 12 55 22 am" src="https://cloud.githubusercontent.com/assets/7041728/16892859/3c83f1a8-4af0-11e6-8cdc-8fcaa8b6abec.png">

**Comment by leo** [comment]
https://github.com/zeit/hyperterm/issues/5
