### ISSUE TITLE
Zoom In/Out Bugs

### ISSUE THREAD

**Issue by aaandrew** [zeit/hyperterm#156]
So with MacOS you can use two fingers on your touchpad to zoom in/out. With hyperterm you're able to zoom in using this gesture, but you're not able to zoom out. Which leaves you with something like:

<img width="200" alt="screen shot 2016-07-16 at 1 08 45 am" src="https://cloud.githubusercontent.com/assets/5565596/16893612/49acee8c-4af2-11e6-81f9-29412778cf17.png">

To replicate: have a windowed terminal, (note that zooming in/out works on fullscreen) then try to zoom in/out on anywhere BESIDES the top-left corner (for some reason it works at this spot even when windowed).

Also a side note: the default terminal doesn't support pinch to zoom.

**Comment by leo** [comment]
I think we should just disable zooming at all. IMHO, people can adjust their font size if something isn't fully readable for them.

**Comment by James-Byrne** [comment]
The zoom in and out using shit-fn-+/-  still works with so I would agree on removing the pinch to zoom functionality.

**Comment by nfcampos** [comment]
@rauchg disabling zoom gestures on the mac is as simple as doing this somewhere on the render process `require('electron').webFrame.setZoomLevelLimits(1, 1);`, i'm just not entirely sure in which file that should go
