### ISSUE TITLE
Default support for 'alt <arrow>'

### ISSUE THREAD

**Issue by aaandrew** [zeit/hyperterm#157]
Looks like alt <arrow> is not supported. The expected behavior is to jump between words, and the current behavior for alt <arrow> is to output ie. (';3C' or ';3D').

**Comment by eljefedelrodeodeljefe** [comment]
Can confirm. Might be related to #161

**Comment by marcbachmann** [comment]
Nope. Not related. Those keyboard shortcuts just aren't mapped to the escape sequences.
`Esc + b` & `Esc + F` are working.

So I tried to write a small plugin. While the plugin system of hyperterm works fine. But sadly I always get an error from hterm. It doesn't support escape sequences: https://github.com/chromium/hterm/blob/23300c0308d9e4ea9bd784807a4e40b1fb1ac69e/js/hterm_vt.js#L1323-L1330

**Comment by montogeek** [comment]
Related https://github.com/zeit/hyperterm/issues/53

**Comment by marcbachmann** [comment]
I have no idea what I did the first time when it didn't work.
But I had to debug the hterm code to get it working. Will continue in #217.
