### ISSUE TITLE
ls (without -l) shows only the first letter of the last column

### ISSUE THREAD

**Issue by jesseditson** [zeit/hyperterm#16]
On the right side of the terminal, you can see the truncated names:

![](http://oi.pxfx.io/0d3v2A2v2P10/Image%202016-07-02%20at%2011.33.32%20AM.png)

**Comment by jesseditson** [comment]
On a second look, it seems that they are wrapping, not missing: ![](http://oi.pxfx.io/2O0Q0e0W3l0C/Image%202016-07-02%20at%2011.36.32%20AM.png)

**Comment by jesseditson** [comment]
This also only seems to happen at some widths - I resized the window with moom, perhaps the calculations were thrown off by the programatic resize?

**Comment by jesseditson** [comment]
I also noticed that it does not wrap responsively - the columns are drawn based on the width at the time of the command, and don't dynamically resize (not specifically an issue IMO, but different than other terminal behavior)

**Comment by rauchg** [comment]
It's possible than the `resize` command on the pty is failing. Sometimes we get ioctl errors.

**Comment by rauchg** [comment]
This might be fixed by `0.2.0`. Let me know if it still happens when you upgrade.

**Comment by rauchg** [comment]
Please retry with `0.3.1`.

**Comment by jesseditson** [comment]
I'm not seeing errors and I'm unable to repro, I'll close and reopen if I ever see it again, fair to assume it's fixed!
