### ISSUE TITLE
Missing unicode support?

### ISSUE THREAD

**Issue by yardnsm** [zeit/hyperterm#161]
When I type non-latin characters, some weird stuff happens. 

![screen shot 2016-07-16 at 1 18 48 pm](https://cloud.githubusercontent.com/assets/11786506/16894183/db53aa00-4b57-11e6-9425-c08cffe0e533.png)

In the screenshot I've typed some hebrew characters, but it also happens when I use other characters like Greek, Chinese, Arabic, etc. Emoji is suffering too... 😢

**Comment by eljefedelrodeodeljefe** [comment]
Taking guesses and investigating on it, I think this has something to do with `hterm` https://bugs.chromium.org/p/chromium/issues/detail?id=218382

**Comment by eljefedelrodeodeljefe** [comment]
I contacted the hterm guys via emial. If the problem really exists there and I think that is likely, this will likely be impossible to fix downstream. We'll see...

**Comment by 6thmonth** [comment]
I found where this error is from. ``` utf8.Decoder.prototype.decode ``` return a weird result. `chromium hterm` team should fix it I think.

**Comment by rauchg** [comment]
This should be fixed for good. I blame a missing `<meta>` tag :( And also for some reason it was happening on some computers and not on others :(

**Comment by misha-marinenko-official** [comment]
I can make hyper support UTF-8

one second and i will be open pull request

**Comment by misha-marinenko-official** [comment]
![2018-11-29 16 19 49](https://user-images.githubusercontent.com/40549120/49227802-ab842700-f3f2-11e8-9275-47459bf01ce6.png)
This is russian on screenshot.
