### ISSUE TITLE
Brew formula for installation

### ISSUE THREAD

**Issue by akarshsatija** [zeit/hyperterm#163]
Is this already available? Couldn't find one.

**Comment by bransorem** [comment]
[Brew Cask has one](https://github.com/caskroom/homebrew-cask/blob/master/Casks/hyperterm.rb)

`brew cask install hyperterm`

**Comment by bransorem** [comment]
This has since been added to the README: #356 

Since it's available in Cask form and documented, maybe this issue can be closed.

**Comment by albinekb** [comment]
Like @bransorem said, you can now install Hyperterm using brew cask, documented in the readme since #356 `brew cask install hyperterm`

Great job everyone! 
Closing this issue 👋

**Comment by plaxdan** [comment]
Note: this has since been updated to `brew cask install hyper`
