### ISSUE TITLE
cd to directory passed as first arguments

### ISSUE THREAD

**Issue by lordgiotto** [zeit/hyperterm#165]
Hi,
I really like this project and the idea to use web technologies for a terminal app, thanks for that!
I want to start using HyperTerm as my default terminal app, but I miss a very important feature: launch it to a specific folder by passing it as first argument. Without this feature I can't integrate it with my workflow (for example atom plugin for open terminal).

Thank you very much :)

**Comment by sasha240100** [comment]
Any updates on this issue?

**Comment by sasha240100** [comment]
@lordgiotto How did you solve this?

**Comment by lordgiotto** [comment]
@sasha240100 I've added macOS specific function for this, trough the `open-file` electron app event (that is triggered on macos only); in addition i've changed the plist file to accept dock file drop. 


So now dragging a file/folder on the hyper dock icon, or using the cli `open` commands with a file/folder as parameter, lets hyper to *cd* to that directory.


For other platform is possible to reuse the same function, but it's necessary to get the argument with yargs or something similar.

**Comment by sasha240100** [comment]
@lordgiotto I am on windows. Can i do something like `$ hyper.exe --folder c:/` ?

**Comment by lordgiotto** [comment]
@sasha240100 No, not yet, it's not implemented. You should do it if you're able to do a pull request, or open a new issue asking for this enhancement.
