### ISSUE TITLE
Feature request: CMD-K to clear scrollback (or perhaps ability to remap CTRL-L)?

### ISSUE THREAD

**Issue by jesseditson** [zeit/hyperterm#17]
On Mac OS terminals, the default command to clear scrollback is command-k, which my fingers are trained to use often. Looks like the closest similar behavior is `clear` or CTRL-L in hyperterm (although it doesn't clear, just puts the prompt at the top, which is a completely acceptable alternative for me). Might be nice to have this functionality for users switching from mac terminal

**Comment by leo** [comment]
Already part of "TODO": `Implement cmd+K to clear`

@rauchg We really need to convert that list into issues.

**Comment by jesseditson** [comment]
oops, I missed that! Closing.

**Comment by leo** [comment]
No problem! Thanks for the effort on creating the issue though 😊
