### ISSUE TITLE
Option/Alt overriding makes it impossible to insert '#'

### ISSUE THREAD

**Issue by OJFord** [zeit/hyperterm#173]
Hyperterm on mac seems to do something funny with option/alt, making it impossible to insert the octothorpe/hash/'number-sign' character `#`.

This means that defining colours in `.hyperterm.js` requires using a different terminal emulator/editor, or pasting in `#` from clipboard.

**Comment by jamox** [comment]
It seems to be working on at least with US layout

**Comment by OJFord** [comment]
@jamox With a US layout presumably you use shift+3 for `#` (`£` with a UK mapping).

Anyway, it seems to be fixed in the latest release.
