### ISSUE TITLE
Default gray is too dark

### ISSUE THREAD

**Issue by rauchg** [zeit/hyperterm#177]
![image](https://cloud.githubusercontent.com/assets/13041/16896782/854b8150-4b52-11e6-8e7b-62a61dcd41a8.png)

I can't see now's ids :D

**Comment by italoacasas** [comment]
Do you have another color on mind ? Maybe something like `#FAFAFA`, but I don't know if that is going to fix now's ids. I use that color on my default theme because is more readable.

**Comment by hharnisc** [comment]
@rauchg could you post the hex value of the hidden text? Will make it a little easier to track down. It's entirely possible it's using a value that's not one of the 16 we've got defined in the ~/.hyperterm.js file

**Comment by mauro-oto** [comment]
This should be closeable after merge of #272

**Comment by albinekb** [comment]
Now that #272 is merged, the colors look like this: (default config)
![image](https://cloud.githubusercontent.com/assets/5027156/17453323/6575a256-5b7a-11e6-91fb-0463c996b519.png)
