### ISSUE TITLE
Question: possible to close a webview without closing the tab?

### ISSUE THREAD

**Issue by jesseditson** [zeit/hyperterm#18]
I can't seem to figure out the command (if there is one) for exiting a webview session without closing the corresponding tab as well. Totally acceptable if that's not supported, but might be a nice feature addition if it's not already in there!

**Comment by jesseditson** [comment]
Haha spoke too soon. CMD-W does it...
![](https://media.giphy.com/media/jUwpNzg9IcyrK/giphy.gif)

**Comment by DouglasMeyer** [comment]
It looks like CMD-W now closes the tab and not just the webview. (this is on 0.7.0.26)

**Comment by jesseditson** [comment]
Yup, CTRL-C now closes the webview!

**Comment by jesseditson** [comment]
Updated my prior comment to avoid confusion.

**Comment by DouglasMeyer** [comment]
Thanks!

**Comment by atdrago** [comment]
@jesseditson Seems like this doesn't work once you navigate to another page within the webview. Can you confirm?

**Comment by ianwalter** [comment]
`CTRL-C` doesn't work for me.
MacOS Sierra + Hyper 0.8.3.873

**Comment by lededje** [comment]
It looks like you need to focus the webview before hitting `CTRL-C`
