### ISSUE TITLE
Airline/Powerline Vim font not working

### ISSUE THREAD

**Issue by mhluska** [zeit/hyperterm#186]
The patched Meslo font doesn't load even after specifying it in the config.

![image](https://cloud.githubusercontent.com/assets/997350/16897852/91eaf55e-4b8d-11e6-9715-7fb7061ffedc.png)

Here's iTerm2 for reference:

<img width="1238" alt="screen shot 2016-07-16 at 7 47 28 pm" src="https://cloud.githubusercontent.com/assets/997350/16897864/05729c66-4b8e-11e6-863e-29eaaba255e1.png">

As an aside, there also seems to be a rendering issue with the vertical columns at 80px and 120px.

**Comment by marcbachmann** [comment]
It works for me. https://gist.github.com/marcbachmann/18df2187b3d1693a43ee60ccbfeab096

**Comment by mhluska** [comment]
I tried your config and I have the same issue. Which version are you on? I'm on version 0.5.0.

**Comment by marcbachmann** [comment]
Yes, also 0.5. What kind of font is yours? Also `.otf`?

**Comment by mhluska** [comment]
Yes `.otf`. I just use whatever is [here](https://github.com/powerline/fonts/tree/master/Meslo)

**Comment by montogeek** [comment]
Different OS?

**Comment by mhluska** [comment]
I'm on OS X El Capitan v10.11.5.

**Comment by mattconde** [comment]
@mhluska for me it turned out to be locale settings in fish.

This time I had symbols working in vim but not in my fish theme (agnoster), ever time it comes down to the same things but always for getting one.

- [ ] supportive font https://github.com/powerline/fonts
- [ ] correct naming of font in fontFamily in `~/.hyperterm.js
- [ ] are you using utf8 where the issue is?

**Comment by mhluska** [comment]
Adding this to my `~/.zshrc` fixed the issue:

```
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
```

**Comment by leira** [comment]
I still got the same issue event after I applied all these LANG variables as "en_US.UTF-8", here is a screenshot in Hyperterm:

![screen shot 2016-09-19 at 2 35 29 pm](https://cloud.githubusercontent.com/assets/39118/18649885/d9118e72-7e76-11e6-937b-8f34285bcc26.png)

Here is in iTerm2:
![screen shot 2016-09-19 at 2 36 02 pm](https://cloud.githubusercontent.com/assets/39118/18649891/de5a292a-7e76-11e6-8ed2-edcab0b19c9a.png)

**Comment by paxpacis** [comment]
For me the solution was to edit .hyper.js **not** .hyperterm.js #2cents

**Comment by mattconde** [comment]
@paxpacis Good spot, hadn't updated my comment since the hyperterm rename.

**Comment by scutdk** [comment]
My problem is powerline in zsh prompt not working. 
Just add some notes, for whatever reason, only "Meslo LG S for Powerline" works for me.
Melso LG M didn't work. Strange. No need to configure LANG variable. Just change from M to S works for me.

OS: macOS 10.12
hyper version:0.8.3
shell: zsh + oh my zsh
