### ISSUE TITLE
Ability to style the path/username

### ISSUE THREAD

**Issue by Frique** [zeit/hyperterm#189]
Hi. I'm having fun theming the window to my liking. Glad to see 0.5.0 made this a bit easier. One thing I'm still missing is the ability to target the first part of each terminal line (`[computer name]:~ [username]$`) in CSS, because it simply appears inside an `<x-row>` along with whatever comes after it. Could that maybe be put in its own separate span tag with a css class?

**Comment by WoodyWoodsta** [comment]
This level of styling/color is up to the shell

**Comment by Frique** [comment]
Oh, I see. That's too bad!
