### ISSUE TITLE
Alternative shortcut for exiting website

### ISSUE THREAD

**Issue by bryceadams** [zeit/hyperterm#2]
I presumed I could exit a website with `ctrl + c` - similar to other terminal processes and it took a little while to figure out it was `command + w`. Not a big deal, but thought I'd mention :)

**Comment by johanbrook** [comment]
I think the same. <kbd>cmd+w</kbd> usually closes the current tab, and one might be afraid to do that while in a webview, since it could cause you to lose the terminal session. <kbd>ctrl+c</kbd> seems suitable, since everybody use that to quit a process.

**Comment by rauchg** [comment]
Good point. I'm going to change that.

**Comment by rauchg** [comment]
Done. Feels much more natural now. Thanks!
