### ISSUE TITLE
[Feature] Cannot Command-Click on URLs

### ISSUE THREAD

**Issue by malonehedges** [zeit/hyperterm#221]
In iTerm and Terminal you are able to hold <kbd>Command</kbd> and click on URLs. Can this be added to the roadmap?

**Comment by leo** [comment]
Yes, please!

**Comment by nkzawa** [comment]
https://github.com/zeit/hyperlinks

This plugin works similar to the requested feature. Please try it out.

**Comment by leo** [comment]
Use the plugin! We might add it as a default one.
