### ISSUE TITLE
I don't want shake the window, how to config

### ISSUE THREAD

**Issue by lipangit** [zeit/hyperterm#222]
As title

**Comment by quarterto** [comment]
I'm guessing you have [hyperpower](https://github.com/zeit/hyperpower) installed? Remove it from `plugins` in your `.hyperterm.js`

**Comment by lipangit** [comment]
If I remove the plugin, I type letters there is no effect.

I want type letter effect, do not want shake window, How can I do next.

**Comment by WoodyWoodsta** [comment]
See this issue: https://github.com/zeit/hyperpower/issues/2
Should probably have opened the issue on that repo in any case! :smile:
