### ISSUE TITLE
Allow plugins to create new windows

### ISSUE THREAD

**Issue by CWSpear** [zeit/hyperterm#226]
I created (ing?) a new [hyperterm-visor plugin](https://github.com/CWSpear/hyperterm-visor) that allows you to activate the HyperTerm terminal globally (and other ~~features~~ feature (but I plan on fleshing it out a bit)), but if you close all the windows, it doesn't look like you can create a new window from a plugin.

Perhaps I'm missing something, but if not, could we refactor `app` to in someway allow for creating new windows?

**Comment by cloudkite** [comment]
This is great! 👍  I use visor mode in iTerm alot so would definitely push me over edge in terms of adopting hyperterm

**Comment by CodeTheory** [comment]
@CWSpear Looks like this was merged with #248?

**Comment by CWSpear** [comment]
Yeah, I have been waiting for a new release (which apparently has happened!).

I'm gonna tweak a little bit of how some things work (i.e. gonna change how the dedicated visor window works) and hopefully get a new release myself up soonish.

**Comment by CodeTheory** [comment]
Alright, cool. Could you close the issue then @CWSpear? 😄

**Comment by albinekb** [comment]
I think we should document that you can do like this in plugins aswell, maybe another issue.
https://github.com/zeit/hyperterm/issues/398#issuecomment-235131717
