### ISSUE TITLE
HyperTerm runs into issues with Jekyll and ASCII characters 

### ISSUE THREAD

**Issue by Snazzyham** [zeit/hyperterm#228]
Trying to run `jekyll build` or `jekyll serve` in hyperterm will give a result of 
`jekyll 3.1.6 | Error:  Invalid US-ASCII character "\xC2" on line 7`  

However, it works fine in the regular terminal.

**Comment by davidguttman** [comment]
Having an issue with a ruby script, maybe it's related?

`windowing.rb:5:in `split': invalid byte sequence in US-ASCII (ArgumentError)`

**Comment by iamstarkov** [comment]
@Snazzyham @davidguttman do you have the same problem in iTerm2 or Terminal App?

**Comment by rastasheep** [comment]
I had same issue with Chef DK, after upgrading to Hyperterm 0.7.0 issue disappeared.

**Comment by iamstarkov** [comment]
@rastasheep thank you. @davidguttman @Snazzyham can you verify on HyperTerm 0.7+ solved problem or that it still exists?

**Comment by davidguttman** [comment]
Solved in `0.7`!

**Comment by rauchg** [comment]
What a time to be alive 🎉
