### ISSUE TITLE
cmd+k support

### ISSUE THREAD

**Issue by rauchg** [zeit/hyperterm#23]
In most terminals it seems like the history goes away upon <kbd>command+k</kbd>. I personally find this annoying, since later I want to scroll back.

We should make it work like `clear`, and if people miss the "history cleaning" behavior, we can add it as a modifier (<kbd>command+shift+k</kbd> for example).

**Comment by rauchg** [comment]
Fixed

**Comment by dpo** [comment]
`command+k` works for me, but the OSX terminal and iTerm also support `printf '\33c\e[3J'`, which does the same thing and can be more easily incorporated into scripts, but which Hyper doesn't seem to honor. Would that be difficult to support?
