### ISSUE TITLE
Cannot type ˜, single quote ' or double quotes " on US international keyboard

### ISSUE THREAD

**Issue by steren** [zeit/hyperterm#230]
My keyboard layout is US international.
When I type the key with the character ', nothing happens in the terminal.
Same if I press shift and press the same key (in order to produce ")

This is a big blocker for me ' 

Pressing space after pressing this key has no effect. It definitely should print a '

**Comment by weslleyaraujo** [comment]
++ same as `~` for example.

**Comment by asantos00** [comment]
Same here with ~. For me it is kind of a critical bug cause of the ~ used for home directory.

Good job with the project!

**Comment by lfuelling** [comment]
The tilde doesn't work on german keyboard layout either. Also the umlauts (ö, ä, ü, ¨) aren't working (displaying as unicode symbols).

**Comment by petetnt** [comment]
(Semi) duplicate of #213

**Comment by diogobeda** [comment]
Being solved at #214
