### ISSUE TITLE
“Zoom” menu on Mac

### ISSUE THREAD

**Issue by uranusjr** [zeit/hyperterm#234]
Native Mac programs usually have a Window → Zoom menu item that resizes the window to an optional size. It maximise the window in the built-in Terminal app.

**Comment by idmarjr** [comment]
@uranusjr You can use `option + full screen` (fullscreen == green button from the window).

**Comment by uranusjr** [comment]
@idmarjr This would require a mouse click. A menu item can be bind to a keyboard shortcut. This would help a lot with my workflow, especially with a terminal app that interacts primarily with the keyboard. #27 also contributes to this problem; the default window size is really really small.

**Comment by idmarjr** [comment]
Fully agreed.
But at least you have a way to maximize window until the zoom menu be added :)
