### ISSUE TITLE
[Question] iTerm's full width position

### ISSUE THREAD

**Issue by olegafx** [zeit/hyperterm#236]
Is there any way to position HyperTerm at the top? And it should take full width, with no title.

Like this one:
<img width="1279" alt="screenshot_18_07_16_16_31" src="https://cloud.githubusercontent.com/assets/867546/16916365/28ec946c-4d05-11e6-9be1-0428df9460a2.png">

I wanted to use custom css, but found no docs…

**Comment by WoodyWoodsta** [comment]
[This plugin](https://www.npmjs.com/package/hyperterm-visor) has that idea in mind. It's very much a WIP though!

**Comment by posabsolute** [comment]
Same, I love how hackable this thing is for me, but the feature I truly love from Item is the ability to fix my terminal at the top screen, full width, and make it pop with a key combination.

**Comment by rauchg** [comment]
@posabsolute should be definitely doable with a plugin. If there are any hooks missing, let me know. 
Thanks @cwspear for taking that up.
