### ISSUE TITLE
$EDITOR not defined with ZSH

### ISSUE THREAD

**Issue by dimitrieh** [zeit/hyperterm#237]
Gives me the following error.

```
# Attempting to open ~/.hyperterm.js with your $EDITOR
zsh: command not found: #
```

While if I put in the command `$EDITOR ~/.hyperterm.js && exit` manually it works.

at the moment my `$EDITOR` is configured with `export EDITOR="/usr/local/Cellar/micro/osx/bin/micro"
`

**Comment by diogobeda** [comment]
#153 is trying to fix that

**Comment by dimitrieh** [comment]
I'll close this one then!
