### ISSUE TITLE
zsh: character not in range

### ISSUE THREAD

**Issue by mhartington** [zeit/hyperterm#238]
When trying to print out a `\u200b` (zero width space) character, hyperterm prints out this warning.

```
zsh: character not in range
```

Steps to reproduce

1) use zsh, (type `zsh`)
2) enter the command `$ echo -e '\n%{\u200B%}'`
3) see error and ponder ( :grin: )

In iterm and osx's default terminal the character is printed out correctly.

**Comment by sergiovilar** [comment]
Same error here..

**Comment by mhartington** [comment]
@sergiovilar would you be able to post any steps to reproduce this? Might help isolate where the issue is.

**Comment by CodeTheory** [comment]
@mhartington Is this error still here in the latest released version?

**Comment by mhartington** [comment]
Sorry, the email when to my spam folder.  Nope looks like it's all taken care of now! Thanks!

**Comment by sergiovilar** [comment]
Issue persists in 0.7.1!
