### ISSUE TITLE
NERDTree in vim issue

### ISSUE THREAD

**Issue by jwoertink** [zeit/hyperterm#246]
I use the [NERDTree](https://github.com/scrooloose/nerdtree) plugin for vim, but when I try to use it in hyperterm, it doesn't function, and gives me a weird display. I've tried changing my fonts, but that doesn't fix it.

![screen shot 2016-07-18 at 10 16 12 am](https://cloud.githubusercontent.com/assets/2391/16923768/c7237a86-4cd0-11e6-9a8c-a1a056046f5a.png)

Here's a screenshot of it in terminal

![screen shot 2016-07-18 at 10 19 59 am](https://cloud.githubusercontent.com/assets/2391/16923852/432457c2-4cd1-11e6-8a2c-953909513532.png)

**Comment by aaronagray** [comment]
I had a similar problem with tmux in HyperTerm. The fix for me was to run tmux with the `-u` flag (`tmux -u`). This tells tmux to explicitly use UTF-8 and solved the problem. Maybe something wonky is happening with UTF-8 in your shell or vim configuration?

**Comment by jwoertink** [comment]
Ah! Interesting. Ok, so I added `set encoding=utf-8` to my `~/.vimrc`, and that fixed it! Thanks for the suggestion.

**Comment by LagartoSeb** [comment]
`set encoding=utf-8` corrects that problem with NERDTree but what about vim airline and its icons?, does anybody have the same problem?

**Comment by amiralles** [comment]
@LagartoSeb, after setting encoding=utf-8 in my .vimrc  file, vim airline start working again.  Are you using the patched fonts for that plugin? (In my case, never worked with std fonts..).
