### ISSUE TITLE
js that runs on shell start

### ISSUE THREAD

**Issue by Jonahss** [zeit/hyperterm#250]
Is there a custom file where I can write javascript that, when hyperterm starts a new window, runs in the context of the electron webview?

Basically a .bash_profile, but one that has access to hyperterm's UI and js context, rather than bash.

I'm asking because I wanted to change the default window size and thought I could just quickly call a `window.resizeTo`.

btw, what's going on in `.hyperterm.js`, `console` and `process` are undefined but it's treated like a js file rather than JSON?

**Comment by rauchg** [comment]
A plugin that uses `onRendererLoad ` (which receives the `window`) would probably help here :)

**Comment by Jonahss** [comment]
Gotcha, I see.

@rauchg What about creating a default dev-plugin that accompanies hyperterm by default, so that users can quickly pile a couple quick lines and adjustments in there. [Atom has the equivalent by way of their init file](http://flight-manual.atom.io/hacking-atom/sections/the-init-file/).

Or are you specifically trying to create a boundary and encouraging users to build plugins for each behavior rather than having a big lump-sum init script?

**Comment by rauchg** [comment]
Yep. I mentioned in another issue I would love to prepopulate `.hyperterm_plugins/local/hello-world` with a very simple plugin :)

And then in the `localPlugins` doc in `config-default` we can document it!
