### ISSUE TITLE
Make Command+9 go to the last tab

### ISSUE THREAD

**Issue by NightlyNexus** [zeit/hyperterm#255]
Web browsers and iTerm2 all go to the last tab (not necessarily the ninth tab) when command+9 is inputted. It would be nice to be consistent with them.
Relevant line:
https://github.com/zeit/hyperterm/blob/fa4033937e3b80554c037efd357b5fd6159372cf/app/lib/containers/hyperterm.js#L45

**Comment by nfcampos** [comment]
safari goes to the ninth tab with cmd+9

**Comment by NightlyNexus** [comment]
Alright, well, I know at least Chrome, Firefox, iTerm2, and Atom go to the last tab. :)
