### ISSUE TITLE
Render images

### ISSUE THREAD

**Issue by cilice** [zeit/hyperterm#258]
I was thinking, why cant we render images in hyperterm like iTerm2 can? It should be easier in an Electron based app.

iTerm2:
<img width="921" alt="screen shot 2016-07-18 at 21 27 21" src="https://cloud.githubusercontent.com/assets/835588/16927603/75cd559a-4d2e-11e6-9a12-af11c24406eb.png">

The used a custom escape code, which is documented here: https://www.iterm2.com/documentation-images.html. The used `imgcat` command can be found here: https://raw.githubusercontent.com/gnachman/iTerm2/master/tests/imgcat

We might not need to implement that exact escape code, but having something similar would be cool.

I was trying to look for a place where I could start, but somehow I cannot figure out where exactly. If anyone is willing to give a tip, it's always welcome.

**Comment by sindresorhus** [comment]
> We might not need to implement that exact escape code

It should support the escape code too, so existing stuff meant for iTerm works in HyperTerm too.

**Comment by montogeek** [comment]
Duplicate of #101

**Comment by cilice** [comment]
Closing this one then, thanks.
