### ISSUE TITLE
Don't close hyperterm when one tab is remaining

### ISSUE THREAD

**Issue by oscarmcm** [zeit/hyperterm#269]
CMD + W when only have one tab dont close hyperterm.

Demo: http://g.recordit.co/B3aFzVPXyh.gif

![image](https://cloud.githubusercontent.com/assets/2553459/16934317/534b7630-4d12-11e6-9193-92f26fea3861.png)

**Comment by albinekb** [comment]
Hello @oscarmcm, thanks for reporting this issue! 🙌

This is fixed in `master` and will make it in to the next release 🎉
