### ISSUE TITLE
Hyperterm should remember the window size upon restart

### ISSUE THREAD

**Issue by johanbrook** [zeit/hyperterm#27]
Currently, Hyperterm always start with a set size.

## Reproduce

1. Open Hyperterm
2. Change the window size
3. Restart Hyperterm
4. See how the window still is the default size

**Comment by johanbrook** [comment]
Can probably be configurable in a config file in the future for new windows. Or for the time being, live in `localStorage` or similar.

**Comment by rauchg** [comment]
By the way, not sure this should live in the user-facing config. It's more of a "private cache" thing.

**Comment by johanbrook** [comment]
True, agree. What I meant was that if a user config is defining a default size for new windows, this cache thing for last size will be redundant anyway, right?

**Comment by rauchg** [comment]
Yes. But I don't know if such an option makes sense beyond the automatic memorization that this would put in place. It's like "implicit config".

**Comment by ppot** [comment]
Would It be needed to remember all windows opened and placing ?

**Comment by wprater** [comment]
Terminal.app will remember size, position, and previous buffer all within individual spaces.  Ideally we'd support all of that.

**Comment by ppot** [comment]
@wprater Are you using terminal.app on Yosemite or new one? In Yosemite, the default terminal only save last state on mine.

**Comment by KyleRayMorgan** [comment]
It should also be noted that not only does HyperTerm not remember size, it doesn't remember which monitor/space it was on. If I have a HyperTerm open on my secondary monitor, and hit `⌘ + N`, a new HyperTerm window opens on my primary monitor. It would be better if it opened  on my secondary monitor. I believe this is related to this issue (Issue #27).

**Comment by ppot** [comment]
@KyleRayMorgan This should be fixed in current master!

**Comment by NicolasParada** [comment]
I would like that it remember fullscreen.

**Comment by orangelynx** [comment]
agree, this should be reopened

**Comment by dmaisano** [comment]
Would also like to see this feature, does not remember it's fullscreen orientation on windows 10

**Comment by dmaisano** [comment]
although not a perfect solution, I am using the [hyperfullscreen](https://www.npmjs.com/package/hyperfullscreen) plugin which launches the terminal in a F11 fullscreen manner. Although I would have preferred for hyper to remember and launch as maximized by default this will have to do. I am able to run the hyper shortcut as a maximized window by editing the properties however this does not work in the case of opening a terminal using the context menu "Open Hyper here" option

**Comment by dmaisano** [comment]
Since this is not a native feature (at least on windows 10 from what I am aware of) I opted to use [hyperfull](https://www.npmjs.com/package/hyperfull) to achieve the desired functionality. There is also [hyperfullscreen](https://www.npmjs.com/package/hyperfullscreen) which launches hyper in an F11 fullscreen window.
