### ISSUE TITLE
Closing tab doesn't kill process running within

### ISSUE THREAD

**Issue by frux** [zeit/hyperterm#278]
1. Open new tab
2. Run something (e.g. I started webserver on port 8081)
3. Close this tab
4. Try to run the same webserver in a new tab
5. Get noticed that this port is in use

OSX El Capitan 10.11.5

**Comment by ekmartin** [comment]
I think this should've been fixed with #263, since it was previously skipping the `rpc.emit('exit', { uid })` call resulting in the behavior you're mentioning.

**Comment by fpereira1** [comment]
#263 was merged, but the latest release is 0.6.0. https://github.com/zeit/hyperterm/compare/0.6.0...master

#263 will be included in the next release

**Comment by CodeTheory** [comment]
I believe this was fixed, as mentioned above. I also can't reproduce this on `v7.0.0`. So I'm going to close this. Feel free to reopen if this still affects you.
