### ISSUE TITLE
Cursor overlaps text containing emoji

### ISSUE THREAD

**Issue by scottluptowski** [zeit/hyperterm#290]
My terminal is set up so that next to the folder name I always display three emojis.

This is how it looks in bash:

![screen shot 2016-07-19 at 11 45 25 am](https://cloud.githubusercontent.com/assets/3178471/16956512/b9f17454-4da6-11e6-84eb-518b84f3253e.png)

This is how it looks in HyperTerm:
![screen shot 2016-07-19 at 11 45 21 am](https://cloud.githubusercontent.com/assets/3178471/16956520/c556284e-4da6-11e6-9778-e5dadeb8102e.png)

And to prove this is emoji related, and not related to the length of the string, I replaced the emoji with text:
![screen shot 2016-07-19 at 11 47 04 am](https://cloud.githubusercontent.com/assets/3178471/16956532/d4a179b6-4da6-11e6-941b-4319f43ba102.png)

**Comment by Charlotteis** [comment]
#154 :)

**Comment by scottluptowski** [comment]
@Charlotteis 😱  Thanks!
