### ISSUE TITLE
Consider comment out configs in `~/.hyperterm.js`?

### ISSUE THREAD

**Issue by amio** [zeit/hyperterm#292]
So we can make user config the highest priority:
`~/.hyperterm.js` > plugins > (the real default config)

For now, if I installed a theme plugin, I won't be able to modify any color again, since the plugins has higher priority than `~/.hyperterm.js`.

**Comment by thomaslindstrom** [comment]
IMO, all default configuration should be commented out. I tried to tackle the issue with theme/user configuration and who should have “the final say” [here, in `hyperterm-seti`](https://github.com/stephensauceda/hyperterm-seti/pull/3), but that solution is not perfect.

**Comment by amio** [comment]
@thomaslindstrom Viewing your reply, suddenly I have an idea inspired by the word "the final say", maybe we could make a plugin running at very last, apply user configuration again.

This method seems works smoothly https://www.npmjs.com/package/hyperterm-final-say (borrowed the name "final-say" from you ;-) )

Except one glitch: the term couldn't auto reload on modification of `fontSize`, but fine with others property. I'm still trying to figure it out.
