### ISSUE TITLE
Full screen top toolbar needs to be designed

### ISSUE THREAD

**Issue by jdsimcoe** [zeit/hyperterm#293]
`Atom` is on the left. `Hyperterm` is on the right. The top toolbar needs to be designed and tweaked in full screen mode:

![screen shot 2016-07-19 at 10 01 14 am](https://cloud.githubusercontent.com/assets/275617/16959120/4ec9aeb6-4d98-11e6-937a-60fa94f9d3ff.png)
![screen shot 2016-07-19 at 10 01 22 am](https://cloud.githubusercontent.com/assets/275617/16959122/5032e92a-4d98-11e6-8849-fd575a502d6a.png)

**Comment by leo** [comment]
https://github.com/zeit/hyperterm/issues/5
