### ISSUE TITLE
Cannot install with brew

### ISSUE THREAD

**Issue by legomushroom** [zeit/hyperterm#295]
When I try to install the hyperterm as described in readme, I have:

```javascript
➜ brew cask install hyperterm
Error: No available Cask for hyperterm
Error: nothing to install
```
But other packages work just fine (for instance `atom` one). What could it mean?

**Comment by booc0mtaco** [comment]
I was able to install it via `brew cask install hyperterm` as of yesterday. Not sure what could be the problem. perhaps try running `brew cask update`, then `brew cask search hyperterm` and see what happens?

**Comment by SpencerCDixon** [comment]
run `brew cask update && brew cask install hyperterm` and see if that fixes it

**Comment by legomushroom** [comment]
@SpencerCDixon's solution works well, thanks a lot guys!
