### ISSUE TITLE
Add chat (gitter)?

### ISSUE THREAD

**Issue by kentcdodds** [zeit/hyperterm#297]
I'd love to chat with other HyperTerm users. Gitter is easy, though limited. Could start there and move if there are issues scaling?

**Comment by JacobDB** [comment]
Seconded. Being able to connect to any channel would be awesome. And support for Mattermost as well (chat system built in to GitLab). This might be better suited as an add-on though.

**Comment by WoodyWoodsta** [comment]
Discord would be great. They're doing some good work :+1:

**Comment by sindresorhus** [comment]
👍 We have had great success with Gitter for [AVA](https://gitter.im/sindresorhus/ava).

**Comment by kaicataldo** [comment]
ESLint has also found a lot of success with Gitter :+1:

**Comment by jamox** [comment]
Apparently they've created a public slack community: [zeit.chat](https://zeit.chat) (https://twitter.com/zeithq/status/756195644021157888)

**Comment by sindresorhus** [comment]
[Slack is not a good fit for open source projects...](https://news.ycombinator.com/item?id=9754626)

**Comment by amilajack** [comment]
Better to say with just one so we dont split the community. I think we should go with gitter.

**Comment by WoodyWoodsta** [comment]
Left slack long time ago in favour of lighter solutions such as Discord
(Gitter definitely falls under the category of light and focused)

**Comment by rauchg** [comment]
https://zeit.chat 🎉
