### ISSUE TITLE
Downloaded => Launched => Uninstalled => Reinstalled => Broken

### ISSUE THREAD

**Issue by pauljakobwhite** [zeit/hyperterm#298]
I clearly messed something up here but I'm hoping someone might have a wild guess as to how to fix. I installed HyperTerm on my Mac then uninstalled with Cleanmymac to download a newer release and now app will not show. The app launches but no windows shows up... I tried reinstalling the original version I used that did launch but no luck. Any thoughts on what uninstalling with cleanmymac might have done, if anything?

Items cleanmymac obliterates
![screen shot 2016-07-19 at 11 01 22 pm](https://cloud.githubusercontent.com/assets/5147679/16966452/f185bb7e-4e04-11e6-854d-81bfd422d679.png)

**Comment by booc0mtaco** [comment]
Check to see if Console.app shows any logs when you open the app. If so, add them here.

**Comment by pauljakobwhite** [comment]
Only this appeared:

```
7/19/16 11:27:44.813 PM HyperTerm Helper[8906]: GVA info: preferred scaler idx 0
```

**Comment by booc0mtaco** [comment]
Oops, forgot to ask... Doesn't appear that it removes the hidden files in your home directory: `.hyperterm.js` and `.hyperterm_plugins/` . Maybe removing (or moving them to new names) will do the trick?

**Comment by pauljakobwhite** [comment]
Worked like a charm! Thanks a million

**Comment by booc0mtaco** [comment]
@pauljakobwhite Cool! if this is all good, I recommend closing it, as the dev.s have quite a bit of work to do with the issue list :)
