### ISSUE TITLE
tmux separator issue

### ISSUE THREAD

**Issue by fundon** [zeit/hyperterm#306]
<img width="615" alt="screen shot 2016-07-20 at 2 43 27 pm" src="https://cloud.githubusercontent.com/assets/27926/16977431/82badd44-4e88-11e6-9409-d93619f637c6.png">

**Comment by AidenMontgomery** [comment]
In your environment variables you will probably see 'LC_CTYPE=' when in a hyperterm session.
Set this to be something that is correct for you e.g. LC_CTYPE=en_GB.UTF-8, it may fix the issue for you, even if it is temporary.

**Comment by fundon** [comment]
Below is my locale info:

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by fpereira1** [comment]
This is a duplicate of #139 and it should be closed.

**Comment by fundon** [comment]
@fpereira1 Ok, Got it.
