### ISSUE TITLE
Cannot write tilde on Portuguese layout keyboard 

### ISSUE THREAD

**Issue by pedrorijo91** [zeit/hyperterm#308]
Using Portuguese layout keyboard on a Yosemite (10.10.5), when I type `~` nothing occurs.

It is kinda problematic because I often want to change directory to `cd ~/folder/anotherFolder` and I have to do `cd; cd folder/anotherFolder` for now...

**Comment by timolins** [comment]
Duplicate. Same problem is discussed here: #213

**Comment by CodeTheory** [comment]
Yes, this is a duplicate. Closing and we can continue discussion in #213.
