### ISSUE TITLE
Can't use '~' in hyperterm

### ISSUE THREAD

**Issue by wcastand** [zeit/hyperterm#309]
Hi, i can't use the '~' in hyperterm right now.
It works on my mac everywhere except in hyperterm.

I can copy-paste '~' but not writing it.

Do you have any idea why ? :)
<img width="271" alt="capture d ecran 2016-07-20 a 11 33 00" src="https://cloud.githubusercontent.com/assets/2178244/16981995/c11a81c2-4e6d-11e6-863b-06bd3f75bb1d.png">

**Comment by marksdk** [comment]
+1

**Comment by javierlopezdeancos** [comment]
+1

**Comment by fpereira1** [comment]
This is a duplicate of #308

**Comment by timolins** [comment]
This is a known issue, which affects not only `~`:  #213

**Comment by CodeTheory** [comment]
Closing in favour of #213. Please contribute to that issue if you have any updates. 😄
