### ISSUE TITLE
Clear works inconsistently

### ISSUE THREAD

**Issue by Dremora** [zeit/hyperterm#318]
Pressing `Cmd-K` (Clear) while a foreground process without a prompt is running (such as `tail -f`) clears everything apart from the last screen of text. When a REPL is running (e.g. shell session), `Cmd-K` clears everything — this is how Clear works in Mac's Terminal for everything.

**Comment by marcbachmann** [comment]
We've fixed that already. Will be in the next release. https://github.com/zeit/hyperterm/pull/215

**Comment by geddski** [comment]
nice! Just ran into this.

**Comment by albinekb** [comment]
It's in 0.7 👌 
Close this one?

**Comment by rauchg** [comment]
@albinekb I think we still might have some issues with cmd+k :\

**Comment by marcbachmann** [comment]
Would be nice if somebody can report the problem if it doesn't work in some cases.

**Comment by darol100** [comment]
This works from my end.

**Comment by darol100** [comment]
We should close this issue.

**Comment by Dremora** [comment]
This seems to work for me now, closing.
