### ISSUE TITLE
Entering a domain without a command opens the domain in hyperterm

### ISSUE THREAD

**Issue by timneutkens** [zeit/hyperterm#322]
Looked through the issue list but didn't find anyone mentioning it. Is anyone else having this?
It's not that much of an blocking issue. Just came across it when accidentally pasting a domain name into hyperterm. Tried it in iTerm2, there it just says command not found.

### Steps to reproduce:

1. Enter google.com
<img width="652" alt="screen shot 2016-07-20 at 21 28 00" src="https://cloud.githubusercontent.com/assets/6324199/17000129/6a88ef8e-4ec1-11e6-9fb9-57ddb9f53f64.png">
2. Press enter
3. You will see the following
<img width="652" alt="screen shot 2016-07-20 at 21 28 09" src="https://cloud.githubusercontent.com/assets/6324199/17000135/70b39be8-4ec1-11e6-8ec6-bc787fba4b4e.png">

**Comment by alanhussey** [comment]
This is an explicit feature of hyperterm. If you watch the video on [the homepage](https://hyperterm.org), it demos this.

**Comment by timneutkens** [comment]
Haha, whoops, to be true I hadn't watched the video.. lol. Thanks for clarifying. Closing this.
