### ISSUE TITLE
Modify terminal's default width/height by tweaking .hyperterm.js 

### ISSUE THREAD

**Issue by amiralles** [zeit/hyperterm#331]
Probably someone already fix this, but here it goes anyway... 
I notice that is not possible to change terminal default size by modifying .hyperpterm.js.
I got this working on my machine (it's a one liner). I can send a pull request if you guys want to.

(I'll also be neat been able to specify the terminal size in cols/rows but I guess that's another issue....)

**Comment by tamagokun** [comment]
#257 waiting to be merged 👍

**Comment by amiralles** [comment]
@tamagokun That's great. Thanks!

**Comment by albinekb** [comment]
#257 is merged, close this one?
