### ISSUE TITLE
Changing inline styles (vim colors)

### ISSUE THREAD

**Issue by Schniz** [zeit/hyperterm#336]
![image](https://cloud.githubusercontent.com/assets/2054772/17020130/a07a8b3e-4f48-11e6-8638-b70e8680cacc.png)

How can I change this blue background? it defined in an inline style and I don't see it in the redux state

![image](https://cloud.githubusercontent.com/assets/2054772/17020194/029fc810-4f49-11e6-9dee-93181c3c82f3.png)

**Comment by bpinto** [comment]
Isn't this a a [vim setting](http://vim.wikia.com/wiki/Highlight_current_line)?

**Comment by Schniz** [comment]
Yeah, but in iTerm it takes another color using the same configuration. So
I wonder how can I config these extra colors 🤔

**Comment by mike-engel** [comment]
@Schniz which setting is this in iTerm? I don't see any colors specific to vim or cursor line?

**Comment by Schniz** [comment]
I guess its just a part of the colorscheme, or maybe my iTerm isn't configured best and it is missing a color and that's what happens:

![image](https://cloud.githubusercontent.com/assets/2054772/17047621/9e782cd8-4fe8-11e6-8fb2-61512c92dbe2.png)

but, now I recall that every time I accidently press `cmd+r` I get:

![image](https://cloud.githubusercontent.com/assets/2054772/17047664/df010a2c-4fe8-11e6-83d7-857ec66bdb86.png)

which is the same. weird. 😦 
Well, I should patch my own vim 😄

**Comment by mike-engel** [comment]
Well, if we could figure out how to tell hterm which color to use, or set something for vim to use, it could go into the config. My vim does it as well and it's super annoying 😁

**Comment by Schniz** [comment]
aha! i found the solution in [this atom-dark repo](https://github.com/joshdick/onedark.vim).
just added the following lines, telling nvim to handle 16-bit colors 😄 

```vim
"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
  if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif
```

**Comment by bpinto** [comment]
I also have that `set termguicolors` set. 👍

**Comment by CodeTheory** [comment]
I assume this has been resolved. Feel free to reopen if it has not.
