### ISSUE TITLE
Ability to use option as META key

### ISSUE THREAD

**Issue by zombie-guru** [zeit/hyperterm#337]
Would be pretty useful since a lot of bash bindings need a META key. For example,

```meta + b```: Back one word
```meta + f```: Back one word

I will take a look at implementing this this week but opening a ticket here just to make sure no work is duplicated or if there are any ideas on this.

**Comment by jamox** [comment]
Seems like a duplicate of: https://github.com/zeit/hyperterm/issues/330

**Comment by CodeTheory** [comment]
I think this is a duplicate. 

It's be great to see an implementation of this, but I'll close this for now to simplify the amount of issues we have.

**Comment by blackmiaool** [comment]
https://github.com/zeit/hyper/issues/330#issuecomment-276880932
This config does the trick.
