### ISSUE TITLE
Pinch & Zoom should be disabled [OS X at least]

### ISSUE THREAD

**Issue by CodeTheory** [zeit/hyperterm#345]
The OS X Pinch & Zoom feature, when zooming in, doesn't allow you to zoom back out. 

In consideration of the fact that hyperterm has text size control, I believe pinch and zoom should be disabled. 

A related electron issue here: https://github.com/electron/electron/issues/3609

_EDIT:_ Looks like the only way you can zoom out with Pinch & Zoom on Mac is to turn on 'Always show scrollbars' from preferences and then hover over the scrollbar and zoom out with the same feature. 

Changing font-size via `CMD + -` bugs out when you've zoomed in.

**Comment by rauchg** [comment]
https://github.com/zeit/hyperterm/pull/326

**Comment by CodeTheory** [comment]
Ah, woops. Thanks. Looks like I only searched issues. Sorry!
