### ISSUE TITLE
LANG environment variable

### ISSUE THREAD

**Issue by pwnall** [zeit/hyperterm#346]
```bash
env | grep LANG
```

shows `LANG=en_US.UTF-8` on Terminal and iTerm, in OSX. It shows nothing in HyperTerm.

I'm guessing the correct default `LANG` value depends on the user's language, and isn't completely trivial to detect. Not having it set adds a bit of friction. For example, `mitmproxy` fails to run with the following error message.

```
Error: mitmproxy requires a UTF console environment.
Set your LANG enviroment variable to something like en_US.UTF-8
```

On a separate note, thank you very much for writing and open-sourcing hyperterm! It is insanely cool! ❤️

**Comment by pwnall** [comment]
Also, in case anyone else runs into this issue, my workaround was to add the line below to my `.bash_profile`

```bash
export LANG="${LANG:-'en_US.UTF-8'}"
```

**Comment by rauchg** [comment]
@pwnall is this something the terminal application should be setting ?

**Comment by gex** [comment]
@rauchg i don't think so, for example for me the result of `env | grep LANG` is nothing (os x 10.11.6, primary language: english, region: hungary)

**Comment by TooTallNate** [comment]
Here's some literature on the subject: http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html

In particular:

> **LANG**
> This variable shall determine the locale category for native language, local customs, and coded character set in the absence of the LC_ALL and other LC_* ( LC_COLLATE , LC_CTYPE , LC_MESSAGES , LC_MONETARY , LC_NUMERIC , LC_TIME ) environment variables. This can be used by applications to determine the language to use for error messages and instructions, collating sequences, date formats, and so on.
>
>If the LANG environment variable is defined and is not null, the value of the LANG environment variable shall be used.
>
> If the LANG environment variable is not set or is set to the empty string, the implementation-defined default locale shall be used.

I'm 👍 for defining it by default.

@gex I seem to have the opposite effect:

``` bash
$ env | grep LANG
LANG=en_US.UTF-8
```

**Comment by TooTallNate** [comment]
Added a PR in #354.
