### ISSUE TITLE
Fullscreen UI Bug

### ISSUE THREAD

**Issue by acondiff** [zeit/hyperterm#347]
There is a place for the traffic lights while in full screen when there doesn't need to be.
![image](https://cloud.githubusercontent.com/assets/806104/17039597/e463e3fa-4f60-11e6-9c5a-16a19dee293b.png)

When the menubar appears, the traffic lights hover over the UI. Expected behavior: The tab bar moves down with the menubar, room is made in the tab bar for the traffic lights.
![image](https://cloud.githubusercontent.com/assets/806104/17039707/49ed4b9e-4f61-11e6-9ecc-2fe4e10dce71.png)

**Comment by matheuss** [comment]
#5
