### ISSUE TITLE
Babel/webpack modules missing from package.json

### ISSUE THREAD

**Issue by Tyriar** [zeit/hyperterm#35]
Trying to build locally (on Linux) I hit:

```
ERROR in Entry module not found: Error: Cannot resolve module 'babel-loader' in /home/daniel/dev/hyperterm/app
```

Installing that then asks for `babel-core`, installing that leads to an `Unknown plugin "transform-react-jsx"` error. An webpack `watch` entry in package.json scripts would be good in addition to more complete `devDependencies`.

**Comment by montogeek** [comment]
I just did a clean installation and everything worked as expected, maybe npm failed, please try again :)

**Comment by rauchg** [comment]
All the missing modules you mention are indeed there. I think @montogeek is right!

**Comment by Tyriar** [comment]
Doesn't this need to mention babel?

```json
  "dependencies": {
    "child_pty": "3.0.1",
    "default-shell": "1.0.1",
    "electron-is-dev": "0.1.1",
    "electron-packager": "7.1.0",
    "electron-prebuilt": "1.2.5",
    "uid2": "0.0.3"
  },
  "devDependencies": {
    "eslint": "2.13.1",
    "eslint-config-standard": "5.3.1",
    "eslint-plugin-promise": "1.3.2",
    "eslint-plugin-standard": "1.3.2"
  },
```

**Comment by montogeek** [comment]
@Tyriar The `package.json` in the main directory if for the Electron app itself, the `package.json` inside the `app` directory is the one used to transpile the app.

Please try to run `./install.sh` first in the main directory, then move to the `app` directory and run `npm i`, it should install all dependencies :)

**Comment by Tyriar** [comment]
Oh that's the issue, why not just have a single package.json though?
