### ISSUE TITLE
Using Istanbul (nyc) code coverage causes exception in HyperTerm

### ISSUE THREAD

**Issue by AidenMontgomery** [zeit/hyperterm#357]
I was looking at adding code coverage to a new node.js project I am working on, using Istanbul with Mocha.
Executing tests with code coverage enabled causes a JavaScript error to occur in the main process of HyperTerm.

### A JavaScript error occurred in the main process
```
Uncaught Exception:
Error: watch /Users/aiden/.node-spawn-wrap-44908-58da72dfca0f ENOENT
    at exports._errnoException (util.js:949:11)
    at FSWatcher.start (fs.js:1433:19)
    at Object.fs.watch (fs.js:1460:11)
    at Gaze._watchDir (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:288:30)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:357:10
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:422:5
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at Object.forEachSeries (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:83:3)
```

No matter where I run the code coverage from HyperTerm pops up the error dialog. I have tried executing the command in HyperTerm, iTerm and Terminal.

![hypertermcoverageerror](https://cloud.githubusercontent.com/assets/364538/17043031/36454548-4ff6-11e6-83e0-b790f64c8a38.gif)

**Comment by matheuss** [comment]
Related: istanbuljs/nyc#324

**Comment by isaacs** [comment]
This looks like it's a shortcoming in https://github.com/tapjs/spawn-wrap

Since HyperTerm is using that (for some reason?  I'm not aware, exactly?  Probably to detect node processes and track them somehow?) and nyc uses it to wrap all node programs in Istanbul coverage, the two instances of spawn-wrap seem to be colliding with and/or overriding one another.

I'm not sure of the best way to approach this.  Supporting multiple wrapper programs is pretty tricky, but probably possible.  (_It's software!_ he says with sarcastic delight that hides his sinking heart.)

**Comment by isaacs** [comment]
As far as I can tell, HyperTerm isn't using spawn-wrap, so this is probably not a collision, but definitely some kind of weird interaction.

Spawn-wrap shouldn't be breaking HyperTerm, but also, HyperTerm should not be susceptible to some program monkey-patching Node either.

**Comment by tkuminecz** [comment]
FWIW I'm seeing this issue as well

**Comment by whitelynx** [comment]
This looks related to #225, #444, and #542.

**Comment by matheuss** [comment]
Related #680

**Comment by matheuss** [comment]
Closing in favor of #225
