### ISSUE TITLE
Rough ETA for windows builds?

### ISSUE THREAD

**Issue by bicubic** [zeit/hyperterm#362]
Would love to know a ballpark ETA for windows builds! With WSL making its rounds, lots of folk are looking for a solid terminal emulator.

**Comment by albinekb** [comment]
Check out #190

**Comment by Daniel15** [comment]
In the meantime, Cmder is pretty good.

**Comment by CodeTheory** [comment]
ETA can be determined from #190. Closing issue. 😄
