### ISSUE TITLE
OS X dragging folder from Finder to get path

### ISSUE THREAD

**Issue by heathervv** [zeit/hyperterm#363]
In terminal it's possible to drag a folder or file into the terminal window and the path to said folder/file is populated. This is useful when you can't quite remember that path to something, but you can find it in Finder!

Is this something that can be implemented in hyperterm? It's definitely not an issue, just more of an enhancement.

**Comment by albinekb** [comment]
#329

**Comment by heathervv** [comment]
That's awesome! Look forward to when either or both of those get merged.
