### ISSUE TITLE
Not able to set cursor width

### ISSUE THREAD

**Issue by akashnimare** [zeit/hyperterm#365]
I tried using this but it's not working -
```css
.cursor-node {
width: 6px !important;
}
```

**Comment by insanityfarm** [comment]
I am able to set my cursor width by adding that CSS into `config.termCSS`. It needs to go in there because you're styling content in the terminal window. If you're putting it in `config.css` that's only for styling the main application window which wraps around the terminal itself.

**Comment by akashnimare** [comment]
@insanityfarm thanks, it worked :dancer:

**Comment by amercier** [comment]
@akashnimare @insanityfarm Which version of Hyper did you use? I can't make it work.

My `.hyper.js`:
```js
module.exports = {
  config: {
    // ...
    termCSS: '.cursor-node { width: 6px !important; }'
  },
};
```

Hyper version: **2.0.0 (stable)**.
