### ISSUE TITLE
What is the end goal of the project?

### ISSUE THREAD

**Issue by xaviervia** [zeit/hyperterm#37]
Hi,

I'm using this already and I really like the aesthetic and of course the fact that uses web tech. Kudos for having something usable day to day so early.

I was wondering though what your vision of what hyperterm will look like is. I've been toying with the idea of a web/electron shell for a while, but my thinking for building a web tech based terminal emulator is to be able to use complex UIs, not to provide a seamless xterm experience using web technologies. 

Is the end goal of the project to be "the Atom of terminals"? 
Do you plan or making it extensible so rich media can be embedded, for example as a result of a command execution (showing image thumbnails on `ls` is the example that comes to mind)? Or is the goal to have it always be 100% compatible with current terminal emulators?

Thanks!

**Comment by rauchg** [comment]
The goal is twofold:
- Provide a beautiful, fast and flawless default experience that is 100% compatible with current emulators.
- Provide a rich and powerful extensibility API (#14) that allows users to customize every aspect of the experience.

Rendering thumbnails after `ls` is something that sounds extremely appealing but if we were to do it ourselves out of the box we'd probably fall short, it could look and feel weird, be unexpected etc.

On this note, the best type of extension that I envision is one that doesn't require altering the underlying machinery and is compatible with a wide variety of shells (fish, zsh, bash). The built-in browser is an example of this, and it might become a "pre-enabled extension" in the future that can be turned off.
