### ISSUE TITLE
Exception whenever I drop a file in ~

### ISSUE THREAD

**Issue by bevacqua** [zeit/hyperterm#378]
<img width="504" alt="screen shot 2016-07-23 at 20 27 31" src="https://cloud.githubusercontent.com/assets/934293/17080797/f250fcc8-5113-11e6-8046-b5020f4ed9e7.png">

**Comment by matheuss** [comment]
Could you provide more info? I can't reproduce this here 😰

**Comment by bevacqua** [comment]
I was just dragging and dropping files to `$HOME` and that exception was raised in an alert in an open HyperTerm instance whenever I did so. There's not much else context I can provide.

**Comment by albinekb** [comment]
Did you move `.hyperterm.js` `

**Comment by bevacqua** [comment]
No. I use a symbolic link though. 

```bash
ln -sfn $PWD/hyperterm/.hyperterm.js ~/.hyperterm.js
```

**Comment by albinekb** [comment]
The error looks a lot like https://github.com/shama/gaze/issues/223

**Comment by bevacqua** [comment]
Will re-open if happens again.
