### ISSUE TITLE
Introduce a footer component

### ISSUE THREAD

**Issue by kielabokkie** [zeit/hyperterm#379]
It would be nice to have access to a Footer component that can be enabled on demand by plugins and give you a space at the bottom of the window to add some information. I'm thinking of a structure like this:

```
<HyperTerm>
  <Header>
    <Tabs>
      <Tab /> ...
    </Tabs>
  </Header>
  <Terms>
    <Term /> ...
  </Terms>
  <Footer>
    <Lines>
      <Line /> ...
    </Lines>
  </Footer>
  <Notifications>
    <Notification /> ...
  </Notifications>
</HyperTerm>
```

Could look similar to [Hyperline](https://www.npmjs.com/package/hyperline) but more integrated and allow multiple lines.

**Comment by CodeTheory** [comment]
Closing due to a related comment by @rauchg https://github.com/zeit/hyperterm/issues/528#issuecomment-236399406
