### ISSUE TITLE
Default OS X keyboard shortcuts are not working

### ISSUE THREAD

**Issue by johanbrook** [zeit/hyperterm#38]
I use <kbd>cmd+h</kbd> to hide all windows belong to an app (can't remember if it's default OS X behaviour or not). It's working in other Electron apps, such as Slack and Atom, when focusing on text inputs. Not sure if this is true for other global OS X shortcuts people have set up.

*Edit:* I tried with <kbd>cmd+option+m</kbd> for minimizing the current window, which isn't working in Hyperterm.

**Version:** 0.2.1.

**Comment by rauchg** [comment]
Fixed
