### ISSUE TITLE
Distribution scripts

### ISSUE THREAD

**Issue by sheerun** [zeit/hyperterm#384]
Hey,

I'm confused. How to package hyperterm for OSX? I don't see any scripts.

**Comment by albinekb** [comment]
Have you looked trough the code?
There's a folder called `scripts` > https://github.com/zeit/hyperterm/blob/master/scripts/package.sh

**Comment by sheerun** [comment]
Oh well, sorry about it

**Comment by sheerun** [comment]
A mention in readme would be nice, though :)
