### ISSUE TITLE
When opening a new tab, it should point to the same directory as the other tab

### ISSUE THREAD

**Issue by leo** [zeit/hyperterm#4]
If you open a new tab within `terminal.app`, the tab will automatically point to the directory of the tab from which you've opened the new one.

It's a pretty handy feature, so I think it should also be in hyperterm!

**Comment by leo** [comment]
Already part of the "TODO" list. IMHO, all of these should be issues though.

**Comment by rauchg** [comment]
I wonder if we should make this the default behavior? Or a default plugin that's enabled built-in?

**Comment by leo** [comment]
It looks like there are people (like @oskarkrawczyk), who don't like this. So the best way to handle it would probably be something that's enabled by default (like with terminal.app, but can also be disabled).

Is there a special reason to make it a plugin? IMHO, it should just be an option.

**Comment by oskarkrawczyk** [comment]
@leo I shouldn't have downvoted the whole comment – I just think this would be a cool addition, but perhaps a bit too much as the default behavior. It's purely subjective, but I never did like this is Terminal.

**Comment by langolf** [comment]
If you use tmux, it already has this feature when you create new pane. 
I think default behavior should be $HOME directory as in others terminals.

**Comment by mendeza** [comment]
I agree with @leo. In various terminal emulators this is typically a user preference set in config.

**Comment by hharnisc** [comment]
Just to call a few things out here. 

This is line that opens the terminal to $HOME directory:

https://github.com/zeit/hyperterm/blob/master/session.js#L26

I like the idea of making this a plugin, but adding it to the default config plugins.

This follows the pattern that Atom editor set out **solid defaults that you can change**

@rauchg I'm reverse engineering some of the code, and the deeper I dig the more I think I need to provide some hooks into the session before I can write a plugin. Does that seem right to you?

**Comment by hharnisc** [comment]
I *think* the above commit should provide what's needed to solve this. For this to work the plugin would need to update the session's cwd when it changes. Still feel like I'm missing something obvious though.

**Comment by hharnisc** [comment]
So I've got this working locally now!

Accepting #174 and adding `hypercwd` to your list of plugins in ~/.hyperterm.js will make this available.

**Comment by hharnisc** [comment]
There's a couple things to think about before closing this out.

Do we add a plugin (like [hypercwd](https://github.com/hharnisc/hypercwd) - yes I'm biased 😜) to the default config or leave it to the user to add it.

If we add it by default will it re-add every time HyperTerm gets updated? If it does, probably will want to prevent that from happening.

P.S. The plugin API is awesome!

**Comment by alexfedoseev** [comment]
Also same directory for new window would be great.

**Comment by leo** [comment]
@alexfedoseev Great idea! But please move your issue over to [hypercwd](https://github.com/hharnisc/hypercwd).

**Comment by leo** [comment]
Who's 👍 on adding [hypercwd](https://github.com/hharnisc/hypercwd) as a default plugin? I definitely am!

Just 👍 or 👎  this comment.

**Comment by matheuss** [comment]
I'm 👍 for adding it as a feature, not as a default plugin 😅

**Comment by alexfedoseev** [comment]
@leo Sure, [done](https://github.com/hharnisc/hypercwd/issues/2)!

**Comment by bevacqua** [comment]
I'm 👎 for adding it as a default plugin. I'd much prefer to be able to pick a default directory with something like this plugin I made: [`hyperterm-working-directory`](https://github.com/bevacqua/hyperterm-working-directory)

**Comment by ppot** [comment]
This is mostly a feature needed when you do a split plan of a current projet, Let say I have one pane for running `npm run dev` and in the other pane `npm start`. So opening the new pane with the same pwd is handy. But not for new tab since they mostly table differents concert or call.

**Comment by leo** [comment]
https://github.com/hharnisc/hypercwd

**Comment by JonathanNathanson** [comment]
HyperCWD doesn't work anymore... get runtime errors when opening new tab.

**Comment by gtdeng** [comment]
@JonathanNathanson  It's working on mine 
<img width="277" alt="image" src="https://user-images.githubusercontent.com/10056474/34842573-c171d42a-f6c0-11e7-9444-d2da6d6c917d.png">

Try updating?

**Comment by danieldelcore** [comment]
I had a look into this last night and i found that all of the underlying logic to do this has already been implemented. The actual problem is that [the cwd is not being pushed into redux](https://github.com/zeit/hyper/issues/1357) so when a new tab or panel is opened, there's no cwd to navigate to. 👍

**Comment by kenmorechalfant** [comment]
hypercwd doesn't seem to work on Windows 10.

**Comment by hyochan** [comment]
Any news on window? Still facing runtime error.

**Comment by KrDimitrov** [comment]
This issue should definitely be reopened. Its seems like hypercwd is dead and broken.... I'd be happy to contribute if needed!

**Comment by dhelbegor** [comment]
did anyone manage to do the open split in the same directory on windows wsl ?. hyper cwd is not working with wsl :/
