### ISSUE TITLE
No close button on an individual tab

### ISSUE THREAD

**Issue by johanbrook** [zeit/hyperterm#40]
It's only possible to close a tab by hitting <kbd>cmd+w</kbd>, which perhaps shouldn't be the only way of closing a tab.

**Version:** 0.2.1

*(I'm filing a bunch of UI stuff now, to keep track of them. Can be triaged).*

**Comment by rauchg** [comment]
@johanbrook spot on. I was thinking of a little thin `x` only shown on tab hover:

<img width="499" alt="screen shot 2016-07-04 at 4 09 06 pm" src="https://cloud.githubusercontent.com/assets/13041/16570789/b40b79c8-4201-11e6-96d7-2edc90aebf92.png">

<img width="502" alt="screen shot 2016-07-04 at 4 10 06 pm" src="https://cloud.githubusercontent.com/assets/13041/16570795/d0736602-4201-11e6-94ab-5ad2ec630eee.png">

The SVG: [x-icon.svg.zip](https://github.com/zeit/hyperterm/files/346895/x-icon.svg.zip)
Let me know if this makes sense or is too subtle.

**Comment by rauchg** [comment]
By the way, I would like the `x` to fade in.

**Comment by johanbrook** [comment]
Totally, that looks nice! Basically like Chrome's close icons' behaviour and appearance. 

I can give this ago if you wanna, unless you're already at it and can add it way faster than I can :)

On tis 05 juli 2016 at 01:13 Guillermo Rauch

<
mailto:Guillermo Rauch <notifications@github.com>
> wrote:

By the way, I would like the

x

to fade in.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/zeit/hyperterm/issues/40#issuecomment-230362617
, or
https://github.com/notifications/unsubscribe/AAasDW0y09xucnuxbhTMPikkqBT0QylGks5qSZOigaJpZM4JErDo
.

https://github.com/zeit/hyperterm/issues/40#issuecomment-230362617

**Comment by rauchg** [comment]
@johanbrook by all means own this one, and let me know if you have any questions

**Comment by rauchg** [comment]
thank you!

**Comment by dbkaplun** [comment]
+1 let me know if you need any help @johanbrook

**Comment by jacobmischka** [comment]
I'm just reading through issues, should this be closed since #58 was merged?

**Comment by Qard** [comment]
Looks like it, yes.
