### ISSUE TITLE
Preinstall is no longer ran when installing plugins (broke hyperambient)

### ISSUE THREAD

**Issue by jamox** [zeit/hyperterm#411]
Recent change: bd5e802e1fb76d36955aae9359f829b3b7f8ce4e changed the install behaviour so that `preinstall` is no longer run and at least [hyperambient](https://github.com/jamox/hyperambient) that used preinstall step for [it's configurable dependencies](https://github.com/jamox/hyperambient/blob/master/preinstall.js) no longer works.

**Comment by rase-** [comment]
Is there a particular reason for dropping lifecycle scripts, btw? Seems somewhat limiting, and it's a little awkward to debug install issues unless documented clearly for plugin authors.

**Comment by albinekb** [comment]
Related to #408

**Comment by rauchg** [comment]
I'm going to revert it. I thought it was a security measure but it didn't make much sense.

**Comment by albinekb** [comment]
https://github.com/zeit/hyperterm/commit/05b491f62c43db100316176b9bb0d8e50487b902
Will be in 0.7.1

**Comment by jamox** [comment]
Awesome, thanks @rauchg!
