### ISSUE TITLE
Support jumping around with modifiers on arrow keys

### ISSUE THREAD

**Issue by controversial** [zeit/hyperterm#415]
`Terminal.app` supports option+◀️ and option+▶️ for jumping forward and backwards in your command. Hyperterm could do this and even take it a step forward with Cmd+◀️ and Cmd+▶️ for jumping to the beginning and end of commands.

This would make typing long commands much much easier and faster.

Thoughts?

**Comment by albinekb** [comment]
I believe this will work after the changes in #214, i have not tested it but that basically makes the line you're editing behave more like an `<input>`,

However cmd+left/right are bound to changing tabs

**Comment by controversial** [comment]
Ah, ok. As far as Cmd+left/right changing tabs, is this re-bindable? I think using Cmd+Shift+left/right would make more sense (it's this way in Safari and Chrome) because then Cmd+left/right could be used to jump to the line beginning/end as it is in native text fields.

**Comment by albinekb** [comment]
Everyone has their own preferences, so this should definitely be configurable!

**Comment by controversial** [comment]
Ok, cool. #214 looks like it’s still bug-ridden, but I’ll close this and
subscribe to comments on that. Thanks!
