### ISSUE TITLE
Test rollup.js for faster startup

### ISSUE THREAD

**Issue by albinekb** [zeit/hyperterm#416]
According to the [rollup wiki](https://github.com/rollup/rollup/wiki):
>unlike other bundlers (such as Browserify or Webpack), Rollup only includes the code you actually need. In many cases, the resulting bundle is a fraction of the size. Even in the worst case scenario it will still be smaller than bundles generated by other tools

https://github.com/rollup/rollup

As discussed here: https://github.com/zeit/hyperterm/commit/c4a142381833aeb89cec9d1c99de05ab72295336

Bundle size can reduce startup time, we should try to use some rollup-tree-shaking-magic to see if it can get better than uglify!

**Comment by rauchg** [comment]
So does webpack 2. Still down for trying.

**Comment by albinekb** [comment]
I'll close this one for now, too many issues that are more important!
