### ISSUE TITLE
Hyperterm got the wrong icon after using it a bit

### ISSUE THREAD

**Issue by cheshire137** [zeit/hyperterm#420]
I'm not sure what happened, Hyperterm initially had its own icon, but now it's using the GitHub Desktop icon:

![hyperterm-wrong-icon](https://cloud.githubusercontent.com/assets/82317/17147840/1a37e0fe-532a-11e6-9a79-e67759d8ca65.gif)

This is the only plugin that I have: `plugins: ['hyperterm-title']`. See https://github.com/parro-it/hyperterm-title.

**Comment by rauchg** [comment]
seems like a Finder bug?

**Comment by rauchg** [comment]
Unless it also happens after restarting it 😢

**Comment by cheshire137** [comment]
I just tried exiting and reopening Hyperterm, the GitHub Desktop icon persists!

**Comment by cheshire137** [comment]
When I use Alfred to open Hyperterm, it shows up in the Alfred window with the right icon:

<img width="573" alt="screen shot 2016-07-26 at 12 21 02 pm" src="https://cloud.githubusercontent.com/assets/82317/17148139/6f52edda-532b-11e6-9193-877bed083541.png">

But once I open the app, it uses the GitHub Desktop icon.

**Comment by matheuss** [comment]
try `sudo killall Dock`

**Comment by cheshire137** [comment]
> try sudo killall Dock

This worked! I'll update this thread again if the icon changes after some usage.

**Comment by cheshire137** [comment]
I'll close this for now since `sudo killall Dock` is a workaround. Mysterious Dock...
