### ISSUE TITLE
vagrant rsync-auto (watch task) no longer working since 0.7.0

### ISSUE THREAD

**Issue by heathervv** [zeit/hyperterm#423]
Hi there! 

Just updated to 0.7.0 and have come across an issue where `vagrant rsync-auto` is no longer working. It's a simple command that's tracking a project folder and then SSH'ing into a server using rsync. It doesn't throw any errors, it just never triggers.

I've tested grunt, gulp, and compass and they're all watching and compiling with no issues.

**Comment by rauchg** [comment]
Can you confirm that rolling back to 0.6.0 fixes it? Here are the download links: https://github.com/zeit/hyperterm/releases/tag/0.6.0

**Comment by heathervv** [comment]
Rolling back fixes the issue!

**Comment by rauchg** [comment]
:O Do you see any errors?

**Comment by heathervv** [comment]
![screen shot 2016-07-26 at 1 49 20 pm](https://cloud.githubusercontent.com/assets/8507983/17149095/c8a029be-5337-11e6-8724-58b362e373d5.png)
No errors, it just seems to not be watching (already tested in Terminal.app to verify that the task itself wasn't the issue)

**Comment by rauchg** [comment]
I wonder if it's the fact that we introduced new `ENV` stuff! 
https://github.com/zeit/hyperterm/blob/master/app/session.js#L27-L30

**Comment by rauchg** [comment]
Try:

```
unset LANG
unset TERM_PROGRAM
unset TERM_PROGRAM_VERSION
```

Random idea but there aren't that many ways in which we alter the actual *runtime* side of things.

**Comment by ekmartin** [comment]
Isn't the only change from 0.6 to 0.7 in regards to `ENV` the `LANG` variable (`-` -> `_`)?

**Comment by rauchg** [comment]
@ekmartin that's the only thing I can think of that could change the behavior of a program

**Comment by ekmartin** [comment]
Hm true, looking at the commit log the `LANG` variable wasn't even added in 0.6.0.

**Comment by heathervv** [comment]
@rauchg Those worked oddly enough!

**Comment by ekmartin** [comment]
Hm, can you try doing `export LANG="en_US.UTF-8"` (with the other variables set) and see if it works? Currently we're exporting LANG as `en_US`.

**Comment by heathervv** [comment]
@ekmartin Yup that also fixes the issue. Screenshot to verify that I reset the three variables and then ran the export:

![screen shot 2016-07-26 at 2 08 46 pm](https://cloud.githubusercontent.com/assets/8507983/17149719/828da39a-533a-11e6-9a2d-3734fecafa84.png)

**Comment by rauchg** [comment]
@heathervv the next auto-update should fix your issue. Thanks for your patience 👼

**Comment by matheuss** [comment]
Can we close it @heathervv? 😌

**Comment by heathervv** [comment]
@matheuss Absolutely! I should've closed this way back then. Thank you for your patience 👼
