### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by dzannotti** [zeit/hyperterm#43]
Terminal colors are slightly different (not respected?)
see

Hyperterm:
<img width="195" alt="screen shot 2016-07-05 at 02 25 00" src="https://cloud.githubusercontent.com/assets/3357072/16571646/dba26266-4257-11e6-9648-141a97464197.png">

Terminal:
<img width="212" alt="screen shot 2016-07-05 at 02 25 12" src="https://cloud.githubusercontent.com/assets/3357072/16571645/dba24182-4257-11e6-871c-d47dcd099fb0.png">

**Comment by rauchg** [comment]
We just have ugly defaults. If someone wants to suggest a beautiful theme, I'm all eyes 🙈

**Comment by dzannotti** [comment]
I noticed that the overall colors are somewhat respected, just a different shade, I think the best way rather than enforce values is to let the user use their own bash colors

**Comment by rauchg** [comment]
@dzannotti either way, even if it's respecting "blue" or "cyan" or whatever, the choice of default color is not a good one. There's little contrast and in general it could be nicer looking (more pastel for example.)

**Comment by johanbrook** [comment]
I looked through the [term docs](https://chromium.googlesource.com/apps/libapps/+/HEAD/nassh/doc/FAQ.md#How-do-I-change-the-color-scheme) (not too helpful) and the source in Hyperterm. Am I being correct in that the way to alter the colours in the term window is to inject "user-css"?

```js
this.term.prefs_.set('user-css', 'objectUrl');
```

**Comment by rauchg** [comment]
Ultimately I always end up reading the source: https://github.com/dbkaplun/hterm-umdjs/blob/master/dist/index.js

Seems like you can pass a custom color palette through the preference system.
https://github.com/dbkaplun/hterm-umdjs/blob/master/dist/index.js#L10815

And these are the default colors: https://github.com/dbkaplun/hterm-umdjs/blob/master/dist/index.js#L577-L1236

Since we probably don't want to override all, you could do something like:

```js
Object.extend({}, lib.colors.colorNames, {
  blue: …
});
```

**Comment by dzannotti** [comment]
I could take this one and add some pastel defaults

**Comment by hharnisc** [comment]
I created one with pastel colors:

![screen shot 2016-07-05 at 10 00 40 pm](https://cloud.githubusercontent.com/assets/1388079/16606303/8e15026a-42fc-11e6-95f6-3b5d206a5d02.png)

But I think a high contrast one looks more cool. It's keying off the cursor and the zeit.co design

![screen shot 2016-07-05 at 9 38 53 pm](https://cloud.githubusercontent.com/assets/1388079/16606331/bb23a4e6-42fc-11e6-9cb8-970d66d7006e.png)

**Comment by rauchg** [comment]
wow they both look 😍

**Comment by hharnisc** [comment]
Thanks @rauchg! Really digging this whole stack. Wonderful job pulling this together! Going to submit a PR with the higher contrast one, since it feels like the right one right now.

```js
// high contrast
this.term.prefs_.set('color-palette-overrides', {
      '0': '#000000',
      '1': '#ff0000',
      '2': '#33ff00',
      '3': '#ffff00',
      '4': '#0066ff',
      '5': '#cc00ff',
      '6': '#00ffff',
      '7': '#d0d0d0',
      '8': '#808080',
      '9': '#ff0000',
      '10': '#33ff00',
      '11': '#ffff00',
      '12': '#0066ff',
      '13': '#cc00ff',
      '14': '#00ffff',
      '15': '#ffffff'
    });
```

```js
// pastel
this.term.prefs_.set('color-palette-overrides', {
      '0': '#272822',
      '1': '#e06c75',
      '2': '#98c379',
      '3': '#e5c07b',
      '4': '#61afef',
      '5': '#c678dd',
      '6': '#56b6c2',
      '7': '#abb2bf',
      '8': '#75715e',
      '9': '#e06c75',
      '10': '#98c379',
      '11': '#e5c07b',
      '12': '#61afef',
      '13': '#c678dd',
      '14': '#56b6c2',
      '15': '#ececec'
    });
```

**Comment by howardroark** [comment]
This great!  Would the concept of default themes that can be toggled be outrageous?  

I really enjoy solarized... http://ethanschoonover.com/solarized

**Comment by rauchg** [comment]
@howardroark this was one of the biggest motivations for this project. Programmatic configuration of every aspect of the terminal through plugins =]
