### ISSUE TITLE
AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [zeit/hyperterm#431]
Would you be interested to provide an [AppImage](http://appimage.org/) for Linux? electron-builder now has support for it that [makes it really easy](https://github.com/electron-userland/electron-builder/issues/504#issuecomment-233170607) to do.

On Ubuntu 16.04, I ran
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs icnsutils graphicsmagick

wget https://github.com/zeit/hyperterm/archive/master.zip
unzip master.zip
cd *-master/

npm install
npm run dist -- --linux=AppImage
```
and it produced a working AppImage.

![linux](https://cloud.githubusercontent.com/assets/2480569/17152182/1198bcc8-5377-11e6-9f38-e90a9a69edbf.png)

**Comment by rauchg** [comment]
`0.7.0` shipped an AppImage. Can you please test it?

**Comment by rauchg** [comment]
Please reopen this issue or new ones if you encounter problems

**Comment by probonopd** [comment]
Sorry, my mistake. Thanks for providing the AppImage! Downloaded, tested, works.

**Comment by rauchg** [comment]
amazing. Could you supply a high resolution screenshot of it with a few tabs open and `uname -a | pokemonsay`? 

Kinda like this:

![image](https://cloud.githubusercontent.com/assets/13041/17152455/b33fc86e-532c-11e6-9197-fdd21d3fe2fa.png)

**Comment by probonopd** [comment]
![screenshot from 2016-07-26 21-36-38](https://cloud.githubusercontent.com/assets/2480569/17152665/144668b0-5379-11e6-8024-049e525d2859.png)
