### ISSUE TITLE
[visual] Tab-bar margin on linux 

### ISSUE THREAD

**Issue by albinekb** [zeit/hyperterm#433]
As seen here https://github.com/zeit/hyperterm/issues/431#issuecomment-235380436
![image](https://cloud.githubusercontent.com/assets/2480569/17152665/144668b0-5379-11e6-8024-049e525d2859.png)

The tab-bar still has margin for the traffic lights

**Comment by matheuss** [comment]
Related: #5

**Comment by rauchg** [comment]
Yeah, I was thinking that we might want to ship a completely different tab style considering no semaphore lights :D
