### ISSUE TITLE
Hover tabs makes font flicker

### ISSUE THREAD

**Issue by albinekb** [zeit/hyperterm#436]
![font](https://cloud.githubusercontent.com/assets/5027156/17153641/d9d60410-537d-11e6-8728-ae1e61bc51c0.gif)

Possibly something to do with font-smoothing or GPU rendering (`transform: translateZ(0);`) ?,
Also makes the prompt text flicker but not as much.

Only present when i have more than one tab open

**Comment by controversial** [comment]
I have exactly the same issue.

**Comment by mike-engel** [comment]
`text-rendering: geometricPrecision` seems like the root cause, at least for my machine. Any other value, or no value at all, seems to fix this. Will investigate settings that property based on screen density like font-smoothing.

**Comment by albinekb** [comment]
#492
