### ISSUE TITLE
how to apply CSS rules to cursor?

### ISSUE THREAD

**Issue by davidascher** [zeit/hyperterm#439]
I was hoping to create an addon to add a pulsing effect on the cursor, but the cursor is drawn inside an iframe, so I don't think the standard theming model works.  Am I wrong?

**Comment by timneutkens** [comment]
Hi David, see is this what you're looking for? https://www.npmjs.com/package/hyperterm-blink
Otherwise maybe just the code :wink: https://github.com/amio/hyperterm-blink/blob/master/index.js#L9 shows how to select it

**Comment by davidascher** [comment]
awesome. thx.

**Comment by timneutkens** [comment]
@davidascher Just saw your tweet, cool effect 👍

**Comment by davidascher** [comment]
Thanks @timneutkens once I had @amio's code it was trivial.
