### ISSUE TITLE
Implement font size <Term> property

### ISSUE THREAD

**Issue by rauchg** [zeit/hyperterm#44]
From the perspective of <HyperTerm> it'd be more elegant if we simply alter <Term fontSize={this.state.fontSize} /> in the render loop.

Then we can capture it in shouldComponentUpdate and manually perform the transformation on the local term reference and return false.

(from #34, ping @jhaynie)

**Comment by jdsimcoe** [comment]
@rauchg Is there a way to set a custom font in `~/.hyperterm.json`?

**Comment by rauchg** [comment]
@jdsimcoe coming

**Comment by jdsimcoe** [comment]
@rauchg Thx!
