### ISSUE TITLE
Plugin installation doesn't use user defined shell

### ISSUE THREAD

**Issue by mike-engel** [zeit/hyperterm#440]
During plugin installation, HyperTerm uses [shell-env](https://github.com/sindresorhus/shell-env) to get the environment variables. The problem is that `shell-env` uses the login shell, without the ability to override. If, like me, you don't have npm in the `$PATH` of your login shell, this command fails and the plugins never get installed.

There are two potential solutions:
1. Send a PR to `shell-env` to allow for a non-login shell
2. Trust that `process.env` will get us what we need and remove `shell-env`

**Comment by rauchg** [comment]
I like 1)

**Comment by albinekb** [comment]
https://github.com/sindresorhus/shell-env/pull/3

**Comment by mike-engel** [comment]
Sweet, thanks @albinekb!

**Comment by leo** [comment]
Added in https://github.com/zeit/hyperterm/pull/447 🎉
