### ISSUE TITLE
Implement font size indicator

### ISSUE THREAD

**Issue by rauchg** [zeit/hyperterm#45]
![](https://cloud.githubusercontent.com/assets/13041/16571918/ba5b7ad8-4217-11e6-8230-5ea1a1faafc9.png)

(from #34, ping @jhaynie)

**Comment by montogeek** [comment]
Will those boxes be configurable via `./hyperterm.json`? Would be great

**Comment by rauchg** [comment]
To not show them at all ?

**Comment by montogeek** [comment]
That is a possibility, I was thinking about colors or size

**Comment by rauchg** [comment]
Yeah since it's non-terminal stuff, semantically I think going with San Francisco makes more sense there.

**Comment by jhaynie** [comment]
i think #57 picks this up.

**Comment by leo** [comment]
Fixed in https://github.com/zeit/hyperterm/pull/57
