### ISSUE TITLE
Can I use it in bash in Windows?

### ISSUE THREAD

**Issue by yeluolei** [zeit/hyperterm#453]
I have tried, but failed with FATAL:render_sandbox_host_linux.cc

**Comment by c0b41** [comment]
probably dups #190

**Comment by yeluolei** [comment]
not exactly, I am talking about windows 10 with ubuntu subsystem, not about the Cygwin. sorry not provide enough information.

**Comment by rauchg** [comment]
The only blocker for Windows support is to get `child_pty` working. Alternatively, we can use `ptyw.js` but making sure we run it as a child process to avoid CPU usage problems.

**Comment by rauchg** [comment]
See: https://github.com/zeit/hyperterm/pull/190

**Comment by CodeTheory** [comment]
Closing in support of singular windows issue at #167.
