### ISSUE TITLE
ñ Letter dont work

### ISSUE THREAD

**Issue by lmichailian** [zeit/hyperterm#457]
On spanish mac (OS X 10.11.6  ) keyboard letter ñ shows <00c3><00b1>

**Comment by CodeTheory** [comment]
Duplicate of #29.

**Comment by lmichailian** [comment]
My Apologies 💃

**Comment by dannegm** [comment]
But, how does repair this?

**Comment by albinekb** [comment]
Try using hyper canary, where we have replaced the terminal rendering lib: https://zeit.co/blog/canary/hyper
