### ISSUE TITLE
HyperTerm crashes on close on OS X

### ISSUE THREAD

**Issue by freebroccolo** [zeit/hyperterm#467]
The commits ed2c810c9ff7c50884a4cc1d3c215d02deede4ad … 72059a7d93f7d18456f8bdf4efcc9ad6c0a084d8 cause HyperTerm to crash with `SIGSEGV` on OS X when HyperTerm is closed. If I rebase on master (2dec8a0da292a7b2017bc9c5e4767bb04bf69378) dropping only these commits the problem doesn't occur.

**Comment by c0b41** [comment]
see this ? #451

**Comment by freebroccolo** [comment]
@c0b41 I see that you reverted one of the commits if that's what you mean, but then there was another commit at 72059a7d93f7d18456f8bdf4efcc9ad6c0a084d8. This last commit seems to be causing HyperTerm to crash on OS X. If I drop these 3 commits I don't encounter the issue.
