### ISSUE TITLE
replace hterm-umd with hterm-umdjs

### ISSUE THREAD

**Issue by dbkaplun** [zeit/hyperterm#47]
[hterm-umdjs](https://github.com/dbkaplun/hterm-umdjs) mirrors hterm's [official git](https://chromium.googlesource.com/apps/libapps/+/master/hterm), whereas [hterm-umd](https://github.com/lalitkapoor/hterm-umd) currently in use seems to be a one-time build, likely to be out-of-date.

In case you ever decide to upgrade hterm. ;)

**Comment by rauchg** [comment]
I've already done that :D It's live in `0.3.1` (https://hyperterm.now.sh/)!
