### ISSUE TITLE
Exit URL preview

### ISSUE THREAD

**Issue by apucacao** [zeit/hyperterm#470]
Hey all,

Thanks for build hyperterm -- it's been awesome so far!

One thing I cannot figure out is how to exit the URL preview mode. Is there a list of shortcuts available somewhere?

Thanks,

Alexis

**Comment by CodeTheory** [comment]
I don't think there's currently a list of keyboard shortcuts, but you can use `ctrl + c` to exit a web view in HyperTerm. Definitely a good idea to have a list of shortcuts associated with HyperTerm somewhere though.  cc/ @rauchg

**Comment by CodeTheory** [comment]
This issue has been open for 6 days now with a relevant answer. If the shortcut doesn't work for you, please re-open an issue.

In any-case I'll open an issue to list keyboard shortcuts somewhere, soon. Thanks for the issue!

**Comment by tylerhou** [comment]
Hi, I'm encountering an issue where `ctrl+c` works on the preview, but not after I've clicked a link on the page. I've upgraded to the latest version of hyperterm and am on macOS.

**Comment by 5minpause** [comment]
Just installed Hyper via homebrew on macOS. I cannot use `ctrl-c` to close a web preview.

Reproduce:

- install hyper (Version 1.0.0 (1.0.0.1303))
- type google.com
- hit `ctrl-c`

Nothing happens. I cannot seem to close a website/preview.

**Comment by emiljohansson** [comment]
@5minpause it seems to be related to #1273. `ctrl-c` works for me only if I click inside the web preview.

**Comment by ppot** [comment]
@emiljohansson Not. It's fixed in #1287

**Comment by 5minpause** [comment]
Alright, it seems to be fixed with version 1.0.1 (1.0.1.1369) for me. Although I need to focus (click) the webview first.
