### ISSUE TITLE
Plugin idea: tmux-like split windows with separate focus and mouse input

### ISSUE THREAD

**Issue by koresar** [zeit/hyperterm#473]
`tmux` console split works fine, until you want to click-to-select a pane with a mouse and scroll it up and down.
I'm using [`tmuxinator`](https://www.youtube.com/watch?v=8DWFvdFttdM) to run tmux from a predefined config file. It simplifies my work a ton.

What would be really hacky and great is to have a plugin or something which splits hyperterm tab onto several tmux-like panes **with a single config file**. But every pane should be a hyperterm itself, so that one can click between the panes, resize them, scroll them with mouse scroll, etc.

If anyone is working on something like that I'd be glad to help. Otherwise, I'm going to write that plugin myself in two months (after my long awaited vacation). :)

**Comment by iamstarkov** [comment]
dup #56 56

**Comment by nathanpalmer** [comment]
Is this really a duplicate of #56? 

I didn't see anywhere in there mentioned the idea of attaching to a tmux session and rendering each tmux window as a separate physical hyperterm tab or pane. I would assume full separate *pane* support would need to come first and then separately support to attach and render from a tmux session. 

From a functionality standpoint being able to natively scroll a tmux session is huge. Hitting Ctrl+b page-up or Ctrl+b+[ definitely gets old after a while.

**Comment by ggascoigne** [comment]
I agree with the original poster.  Being able to use iTerm to attach to tmux as well as manage all of the panes as though they were native iTerm windows or panes is a really useful feature.  You get all of the convenience of tmux without having to change your interaction model.
