### ISSUE TITLE
Download bar of brew install cascades instead of refreshing the current line

### ISSUE THREAD

**Issue by dotlouis** [zeit/hyperterm#477]
![brew-install](https://cloud.githubusercontent.com/assets/1891109/17208526/632269f2-54b9-11e6-825e-f205e0345b46.gif)

This has curiously happened to me only on the `brew install` command.
Other similar commands that display a download bar such as `npm install` work as expected.

**Comment by iamstarkov** [comment]
last line has last symbol on the next line, can you try to do that with wider window?

**Comment by iamstarkov** [comment]
so there will be no overflow

**Comment by dotlouis** [comment]
Damn, you were right.., it works with a wider window.
Sorry for the false issue.

**Comment by iamstarkov** [comment]
@dotlouis 👍
