### ISSUE TITLE
Switching tabs using cmd+arrows no longer works

### ISSUE THREAD

**Issue by mawie81** [zeit/hyperterm#486]
In iTerm2 I´m able to switch to the next or previous tab using cmd+arrow left/right.
I´m pretty sure this was working already when using version 0.6. but currently it´s not working anymore.

**Comment by albinekb** [comment]
https://github.com/zeit/hyperterm/releases#the_unexpected
https://github.com/zeit/hyperterm/pull/217#discussion_r72173465

That's the new default, and there is currently no way to change this 😕

**Comment by mawie81** [comment]
Ok thanks, did not notice that.

**Comment by Monte9** [comment]
`command+alt+left arrow` -> move Left
`command+alt+right arrow` -> move Right

**Comment by deitch** [comment]
No way to override this in preferences? Trying shifting from iTerm2, really enjoying hyper, but the Cmd-Left / Cmd-Right is deeply ingrained.

**Comment by chabou** [comment]
All keymaps can be modified now: https://hyper.is/#keymaps

**Comment by abigger87** [comment]
`cmd+[` switches to the left
`cmd+]` switches to the right
Provided by @chabou answer above.
