### ISSUE TITLE
In zsh trying to open websites results in an error

### ISSUE THREAD

**Issue by jdsimcoe** [zeit/hyperterm#50]
In `zsh` with [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) installed trying to run `google.com` or `apple.com` from Hyperterm produces this error:

```sh
❯ google.com
zsh: command not found: google.com
```

When I `exec bash` and run `google.com` loading websites works perfectly. Any thoughts?

**Comment by rauchg** [comment]
Nice. I'll fix [the regexp](https://github.com/zeit/hyperterm/blob/master/app/term.js#L113) :D Looks easier than I was expecting.

Can you tell me what the error looks like with `http://google.com/` ?

**Comment by jdsimcoe** [comment]
@rauchg Here it is:

```sh
❯ http://apple.com/
zsh: no such file or directory: http://apple.com/
```

**Comment by jdsimcoe** [comment]
👍

**Comment by rauchg** [comment]
Added support for fish, dash (`sh`), zsh. Anything else I'm missing?
