### ISSUE TITLE
fontSize doesn't apply?

### ISSUE THREAD

**Issue by kevinSuttle** [zeit/hyperterm#502]
Anyone else seeing this?

**Comment by mguldev** [comment]
Works for me.

**Comment by kevinSuttle** [comment]
<img width="596" alt="screen shot 2016-07-29 at 3 01 56 pm" src="https://cloud.githubusercontent.com/assets/95672/17260294/8cc39580-559d-11e6-8927-f1b68b0170c0.png">

**Comment by kevinSuttle** [comment]
Oh right. Unitless. Duh.
