### ISSUE TITLE
Could not input Chinese or Japanese characters.

### ISSUE THREAD

**Issue by qiwenmin** [zeit/hyperterm#504]
Open the Chinese or Japanese IME and type, the key is directly sent to the terminal. For example, when typing 'a' in Chinese PinYin IME, the IME should hint the Chinese character '啊', after typing spacebar, '啊' should be sent to the terminal. But now 'a' is sent to the terminal.

-

HyperTerm 0.7.1
Electron 1.2.8
darwin x64 15.6.0

**Comment by joaocampinhos** [comment]
Related: #66.
Should be fixed by #214 :pray:
