### ISSUE TITLE
Close button icon asset is missing

### ISSUE THREAD

**Issue by insanityfarm** [zeit/hyperterm#505]
Just noticed that the tab close button "X" icon no longer exists. The developer tools console contains this error:

`file:///Applications/HyperTerm.app/Contents/Resources/app/assets/icons.svg#close Failed to load resource: net::ERR_FILE_NOT_FOUND`

I opened the app package contents in Finder and confirmed that I can't find icons.svg anywhere. There is no assets directory inside Hyperterm.app/Contents/Resources/app/.

**Comment by leo** [comment]
Fixed in https://github.com/zeit/hyperterm/commit/2a13f3a38f686131d479947e7a36e64ef1f2bd76

**Comment by insanityfarm** [comment]
Sorry to reopen, but did I miss something here? I could've sworn this was fixed, but I have the latest version and it's missing the asset again. Same issue as I initially reported.

**Comment by ekmartin** [comment]
It hasn't been released yet @insanityfarm, should be fixed in the next version. If you're eager to try it out you can create your own `HyperTerm.app` by cloning and running `npm install && npm run pack`. More info here: https://github.com/zeit/hyperterm#contribute

**Comment by insanityfarm** [comment]
Ah, thank you. I had misread Github and thought it was already released.
