### ISSUE TITLE
Non-retina text rendering is bad

### ISSUE THREAD

**Issue by zpao** [zeit/hyperterm#51]
There's a rule, presumably down in Electron, that is setting `-webkit-font-smoothing: antialiased` for `x-screen`. Perhaps I'm extra sensitive to this, but this looks absolutely terrible on non-retina screens. When I toggle that rule in the inspector everything looks great. Personally I think that also looks better on a retina screen. It might be worth considering enforcing subpixel-antialiasing (IMO always, but could be on a media query for < 2 pixel density), or eventually some setting even.

**Comment by rauchg** [comment]
@zpao +1000. I've been seeing some screenshots from non-retina that have wanted to make me cry.

**Comment by johanbrook** [comment]
I actually think antialiasing looks bad on Retina too. Compare screens below.

![skarmavbild 2016-07-06 kl 01 57 00](https://cloud.githubusercontent.com/assets/437261/16603532/0436f802-431d-11e6-8dbf-f03002ea90b3.png)

![skarmavbild 2016-07-06 kl 01 57 07](https://cloud.githubusercontent.com/assets/437261/16603536/0af7bc08-431d-11e6-8c7b-ed293cc1fad9.png)

The non antialiased one has clearer colours and more legible typography imo (might only be me). The antialiased text looks a bit weak: the black from the background sort of bleeds into the glyphs. Compare with iTerm:

<img width="786" alt="skarmavbild 2016-07-06 kl 02 00 00" src="https://cloud.githubusercontent.com/assets/437261/16603588/78c5aaf6-431d-11e6-92c6-86b27538dd27.png">

**Comment by zpao** [comment]
@johanbrook I agree. I've lost the "just use subpixel-antialiasing all the time" argument too many times though so I hedged my bets 😛

**Comment by zpao** [comment]
In case anybody else comes across this and it's not "fixed" the way you want, you can use `~/.hyperterm.js` to override.

```js
    termCSS: `
      x-screen {
        -webkit-font-smoothing: subpixel-antialiased !important;
      }
    `,
```

**Comment by ali** [comment]
Hey all. I noticed this same issue at work today after customizing the fonts in my hyperterm config. My fonts looked great on my laptop's retina display, but looked kinda 💩 on my external monitor. I played around in the devtools and can confirm the above fix worked out for me.

Anyway, here's a hyperterm theme I made that adds subpixel-antialiased font smoothing: https://github.com/ali/hyperterm-subpixel-antialiased

**Comment by leo** [comment]
People without retina displays will have to use this package: https://github.com/ali/hyperterm-subpixel-antialiased

**Comment by tuxracer** [comment]
Even on a retina display this default looks awful on macOS

**Comment by kompot** [comment]
`-webkit-font-smoothing: subpixel-antialiased !important;` hack does not seem to work on Hyper 2.

Any suggestions?

**Comment by albinekb** [comment]
Hyper 2 uses https://github.com/xtermjs/xterm.js instead of `hterm` like we did previously. @kompot I'd recommend you to go over there and search through the issues 👍 

🚨*warning* in the upcoming 3.0 release of `xterm`, they will change to rendering on webgl/canvas, don't know how font smoothing is handled in there. Hyper will adopt it in the future when it's released. I think VS Code is already testing this code so if you want to try how it will be in the future you could test it there.

**Comment by bgw** [comment]
@kompot

> `-webkit-font-smoothing: subpixel-antialiased !important;` hack does not seem to work on Hyper 2.

[Setting `body { -webkit-backface-visibility: unset; }` seems to do the trick for me.](https://github.com/bgw/dotfiles/commit/25bb078f5154cbdf6e13333399d0da0591c9e665)

The `backface-visibility` change was added in #1602 to work around some cases where Blink would enable/disable subpixel antialiasing due to animations (#1490). Unfortunately, it does this is by breaking subpixel antialiasing.

**Comment by kompot** [comment]
Unfortunately doesn't seem to change much on macOS.

Here are three windows. Top is hyper, terminal.app in the middle, vs code on the bottom 3rd.
Hyper's font rendering produces thin and unpleasant lines ;( * i know some people prefer that, yes, but could not find a way to get rendering like in terminal.app or iTerm2 *

![image](https://user-images.githubusercontent.com/231635/33574339-02418b1c-d939-11e7-9842-99e04b8dfc2d.png)

**Comment by hofm** [comment]
Same problem here, too. Looks fine on the built-in retina display of the MacBook; unusable with an external non-retina monitor. Any suggestions?
[
![screen shot 2018-02-27 at 13 40 52](https://user-images.githubusercontent.com/2122291/36729398-5180a726-1bc4-11e8-8c8e-1c3582ed8a8f.png)
](url)

**Comment by jq-87** [comment]
https://github.com/bgw/dotfiles/commit/25bb078f5154cbdf6e13333399d0da0591c9e665

This fix does not work for me. I am on version 2 on OSX 10.12.6

Anyone know of a fix?

**Comment by albinekb** [comment]
Can you try setting `fontWeight` to `100` or `lighter`, it should accept any valid css-font-weight value 👍

**Comment by samishchandra** [comment]
None of the above things worked for me. Type this in the command line and reboot. This setting also stays between reboots.

`defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`

**Comment by TinyChief** [comment]
> None of the above things worked for me. Type this in the command line and reboot. This setting also stays between reboots.
> 
> `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`

Here is the actual problem explained: https://ahmadawais.com/fix-macos-mojave-font-rendering-issue/

Now fonts look smoother, but another problem appears after rebooting - gaps between glyphs:

![изображение](https://user-images.githubusercontent.com/34870422/57735686-234ac300-76ae-11e9-9b34-85f51e2159e5.png)
![изображение](https://user-images.githubusercontent.com/34870422/57735699-2f368500-76ae-11e9-8a57-c5021179d17e.png)

**Comment by rmnbrd** [comment]
To edit the font smoothing setting at application-level and not system-wide, 
here's the trick:
```
defaults write co.zeit.hyper CGFontRenderingFontSmoothingDisabled 0
defaults write co.zeit.hyper.helper CGFontRenderingFontSmoothingDisabled 0
defaults write co.zeit.hyper.helper.EH CGFontRenderingFontSmoothingDisabled 0
defaults write co.zeit.hyper.helper.NP CGFontRenderingFontSmoothingDisabled 0
```
