### ISSUE TITLE
Fails to display anything

### ISSUE THREAD

**Issue by austinwade** [zeit/hyperterm#527]
Hello all,

I am running Hyperterm 0.7.1.36 on OSX El Capitan 10.11.6.

When I start Hyperterm, the app opens but does not display anything within the console:

![](https://i.gyazo.com/610c27b134ad7ba541414bb1368559ad.png)

This problem has occurred since the first time I opened the app after upgrading to version 0.7.

I tried clearing the Hyperterm directory within _~/Library/Application Support/_ along with a restart, unfortunately to no luck.

Could someone help me? Thank you so much!

**Comment by albinekb** [comment]
Hello @austinwade, are you able to join the HyperTerm slack? I think it would be easier to debug that way 🚑 
[![Slack Channel](https://zeit-slackin.now.sh/badge.svg)](https://zeit.chat/)

If not, can you try pressing `alt+cmd+i` or go to `View` -> `Toggle Developer Tools` in the menubar?

 👋

**Comment by albinekb** [comment]
Chatted with @austinwade and found out what the problem was: https://github.com/zeit/hyperterm/blob/master/lib/components/term.js#L31

If you set `cursorColor` to anything that [color](https://www.npmjs.com/package/color) can't parse, the error is not handled and results in a broken hyperterm 😭

**Comment by jwhitmarsh** [comment]
I'd love to start contributing to this project, and this seems like a good place to start - there isn't much in the README in regards to contributing, so can I just crack on is there anyone who could point out some gotchas for me?
