### ISSUE TITLE
Statusbar with pluggable components?

### ISSUE THREAD

**Issue by lordgiotto** [zeit/hyperterm#528]
Hi, it's only an idea I was thinking about and I wanted to discuss with you: a bottom statusbar could be a great addition, for instance to display informations relative to the context of the working directory/git status/etc.

An example from "black-screen":
![image](https://cloud.githubusercontent.com/assets/5115382/17273885/f349ae50-56c6-11e6-9463-87337e96dcd6.png)

I'm aware it should be implemented through plungin (like [hyperline](https://github.com/NickTikhonov/hyperterm-hyperline)), but the downside is that, if everyone adds his statusbar implementation, sooner or later users will have to choose features from one or live with more than one sidebar in hyperterm.

What if hyperterm implements his own statusbar that developers could "populate" with their plugins? It could be a cleaner solutions for both developers and users 😉

**Comment by CodeTheory** [comment]
Related? #379

**Comment by rauchg** [comment]
Should be done with plugins, unless we start seeing that a good number of people are loading a statusbar plugin and then other plugins that alter it.

**Comment by lordgiotto** [comment]
@rauchg My idea was exactly to eventually avoid a "statusbar plugins hell", where every dev implements his statusbar :)
Another solution could be a statubar plugin that expose apis for other devs to create their plugins for it. It's less clean for sure, but I understand that you prefer to keep this thing modular ;)

**Comment by CodeTheory** [comment]
I believe @lordgiotto does have a point @rauchg.

But then again, HyperTerm has much more important things to deal with right now. Perhaps a convincing PR would sway the maintainers _hint_.
