### ISSUE TITLE
Option-arrow does not act like terminal.app

### ISSUE THREAD

**Issue by jesseditson** [zeit/hyperterm#53]
When modifying commands in other terminal apps (and text editors), option-arrow acts like the `b` and `w` commands in `vi`, jumping to the next word boundary. In hyperterm, it instead prints `;3D` and makes the `^G` noise.

Note that option-delete acts as expected, deleting to the nearest word boundary.

**Comment by rauchg** [comment]
Great find @jesseditson

**Comment by montogeek** [comment]
I get the same behavior in iTerm, it prints: `[C` to right and `[D` to left, weird

**Comment by atdrago** [comment]
Unfortunately, this is a non-starter for me :(

**Comment by sifex** [comment]
+1. This and Option+Backspace is killer features for me.

**Comment by crispossa** [comment]
+1. 15 minutes using the HyperTerm and tried to use the Opt+Arrow Left. ;3D on my face!

**Comment by mismith** [comment]
This is also going to make it hard for me to switch. Is there documentation somewhere on how plugging into key-bindings?

**Comment by oarrabi** [comment]
Same here, after finding and tweaking a great theme, I hit alt+delete and nothing happens :(

**Comment by rauchg** [comment]
This is in the process of being fixed.

**Comment by adamstac** [comment]
+1

I use option + b and option + f quite a bit.

**Comment by liancheng** [comment]
@adamstac The following config works for me for `option + b` and `option + f`:

```javascript
module.exports = {
  config: {
    modifierKeys: {
      altIsMeta: true
    }
  }
}
```

**Comment by caesar** [comment]
Thanks @liancheng, that makes Alt+Backspace work which was driving me crazy!
Unfortunately Alt+Left and Alt+Right still don't work...

**Comment by pferreir** [comment]
This doesn't seem to work yet. Maybe the ticket should be re-opened?
