### ISSUE TITLE
Linux fatal error

### ISSUE THREAD

**Issue by binjospookie** [zeit/hyperterm#538]
Hello!
Faced with...

![490268f1993a0141b074dde72ac9dfaa](https://cloud.githubusercontent.com/assets/8722478/17292681/3e58ff44-57f4-11e6-8744-d85bf8db73ff.png)

What should I do?

P.S. Ubuntu 14.04

**Comment by c0b41** [comment]
npm issue [#12439](https://github.com/npm/npm/issues/12439)

**Comment by albinekb** [comment]
Use `https://npms.io/search?term=hyperterm` or `https://www.npmjs.com/search?q=hyperterm` as a workaround 👍

**Comment by binjospookie** [comment]
@albinekb thank you!
