### ISSUE TITLE
Can Type ~

### ISSUE THREAD

**Issue by MatthD** [zeit/hyperterm#539]
Hello !

First thanks to all this job :) 
I am not able to insert ~caracter on hyperterm (OSX french keyboard)
I have read all opened & closed issues but did not find any solution. Is There a bypass while your are on it ? :)

**Comment by MrRio** [comment]
Try this? https://github.com/zeit/hyperterm/pull/521

**Comment by MatthD** [comment]
Done swtiching to us keyboard ! but not working too 😢

**Comment by CodeTheory** [comment]
Duplicate of #466. A fix is in progress. 😄
