### ISSUE TITLE
[Linux] AppImage doesn't run on Fedora

### ISSUE THREAD

**Issue by efegurkan** [zeit/hyperterm#551]
Hello,

The AppImage doesn't work on Fedora 24.
Here is the console output.
`/tmp/.mount_cufLPl
$XDG_DATA_DIRS is missing. Please run /tmp/.mount_cufLPl/AppRun from within an AppImage.
`

I believe there is something with how it is bundled with AppImage. I am not sure though. Maybe @probonopd has some ideas ?

**Comment by probonopd** [comment]
The error message `$XDG_DATA_DIRS is missing` [comes from](https://github.com/probonopd/AppImageKit/blob/70ac2923050aeb52bee1837c7a0ec046714087d1/desktopintegration#L211-L220) AppImageKit's desktopintegration script, but I doubt that it is what prevents HyperTerm from running on Fedora 24.

**Comment by gfortaine** [comment]
@efegurkan @probonopd export XDG_DATA_DIRS="/usr/local/share:/usr/share"

**Comment by efegurkan** [comment]
@gfortaine @probonopd I accept this as a Workaround. This was causing AppImage to not start on F24. It might need further investigation to see if it is really a bug or not. 

> Do you see any other console output?
@probonopd there was nothing else.

**Comment by probonopd** [comment]
How is `XDG_DATA_DIRS` set on Fedora 24 by default?

**Comment by probonopd** [comment]
Something to watch for - is this a F24 feature/bug?

**Comment by efegurkan** [comment]
I am not able to check it with F23. On Ubuntu 14.04 AppImage works just fine. 

I assume XDG_DATA_DIRS is not had to be set to comply with the standard according to this line on the standard. Not sure if it is a ~~bug~~ feature on the F24.

[If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used.](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
