### ISSUE TITLE
Possible to switch windows with ⌘-[0-9]?

### ISSUE THREAD

**Issue by hairyhenderson** [zeit/hyperterm#558]
I've mostly used Terminal.app for the past few years, and I tend to have a number of different windows open (not tabs), and arrange them in grids (with keyboard shortcuts, using [Spectacle](https://www.spectacleapp.com)). What makes this work really well is that the first 9 Terminal windows can be switched between with ⌘-n (where n is the window's index).

Would it be possible for HyperTerm to adopt this behaviour as well?

**Comment by hhsnopek** [comment]
The current behavior of `cmd-n` is to switch tabs, as does chrome and many other applications on OSX - I don't think HyperTerm well end up adopting this behavior, they could make it customizable so you could control the windows index...

**Comment by bevacqua** [comment]
FYI `hyperterm-tab-numbers` does this.

**Comment by hairyhenderson** [comment]
@hhsnopek - thanks for pointing that out - I _totally_ didn't notice that... I don't generally use tabs in my terminal, and I've gotten used to using `⌘-⇧-[`/`⌘-⇧-]` to switch between tabs.

Sounds like a plugin is definitely in order here. I'm _brand new_ to HyperTerm (so's the rest of the Internet, I guess), so I haven't really figured out plugins yet :wink:

@bevacqua - cool, thanks for the tip

**Comment by albinekb** [comment]
Duplicate of #203 🙌

**Comment by hairyhenderson** [comment]
Thanks @albinekb - didn't find that one when I searched :grin:
