### ISSUE TITLE
Split panes

### ISSUE THREAD

**Issue by CodeTheory** [zeit/hyperterm#56]
Hey! I'm loving using this so far, there's only _one_ thing missing that helps me with my workflow. 

I'd love to see multiple panes in tabs. For example, you could use `CMD+D` for a horizontally split pane or `CMD+SHIFT+D` for a vertically split pane from the currently selected. I don't have any particularly good ideas on how to navigate the panes with keyboard commands. Atom uses `CMD+K` then `CMD+[directional arrow]` to navigate between split panes.

Anyway, I'd absolutely love to see this feature in hyperterm, I hope it's possible!

**Comment by rauchg** [comment]
Yes. It's possible and we'll do it.

**Comment by CodeTheory** [comment]
Here's a shot at trying to be helpful towards the process of getting this done.

I took your sketch file from `hyperterm-art` and tried to prototype what it could possibly look like. 

![image](https://cloud.githubusercontent.com/assets/1695613/16603244/ddc5e7fc-431a-11e6-8cf7-209864028858.png)

![image](https://cloud.githubusercontent.com/assets/1695613/16603251/ea26d074-431a-11e6-894b-a7e4d23e65f4.png)

**Comment by rauchg** [comment]
wow that looks incredibly beautiful. Thank you @CodeTheory

**Comment by nuke99** [comment]
@CodeTheory can you  share the code ? I was about do the same thing when I came across this thread

**Comment by CodeTheory** [comment]
@nuke99 There isn't any code from my side. The screenshot I shared was a design prototype addition to the sketch file found in the `hyperterm-art` repository.

**Comment by sdaitzman** [comment]
I'd love to see the interface behave similarly to iTerm2

**Comment by FalkoJoseph** [comment]
Can't wait for this! 😎

**Comment by CWSpear** [comment]
@CodeTheory You'd probably actually want nested over each split pane, as well as the "parent" window tabs on top.

See iTerm:

![screen shot 2016-07-18 at 11 06 17 am](https://cloud.githubusercontent.com/assets/495855/16925141/aa2903e0-4cd7-11e6-9dbe-02f1e404a729.png)

**Comment by CodeTheory** [comment]
@CWSpear I was actually just thinking about this. I don't know how @zeit plan to do it though!

**Comment by nfcampos** [comment]
we might want to use this for rendering the split panes https://github.com/tomkp/react-split-pane

**Comment by iamstarkov** [comment]
@nfcampos that sounds good

**Comment by rdewolff** [comment]
Looking forward having that feature too!

**Comment by solomonhawk** [comment]
@rauchg How do you want to move forward on this? We chatted briefly on Twitter - I'd like to understand what your plan is for this feature.

**Comment by ekmartin** [comment]
I've started working on this. @solomonhawk I'm pretty certain that it needs to be in core though, as it requires quite significant changes to the current structure (sessions and so on).

I'm sure it'll be a while until I have a PR done, getting nested splits working smoothly is a pretty large change. So if anyone's already working on it and beat me to it, :shipit: 👍. Otherwise I'm on Slack if anyone wants to brainstorm eventually.

**Comment by tuongaz** [comment]
Can't wait for this

**Comment by solomonhawk** [comment]
@ekmartin Wonderful, I'll look for you on slack.

**Comment by iamstarkov** [comment]
@ekmartin @solomonhawk hi, can you help me with finding slack you are talking about?

**Comment by ekmartin** [comment]
Looks like you found it @iamstarkov, but if anyone else's looking it's here: https://zeit.chat/

**Comment by c4milo** [comment]
This is the only feature stopping me from using hyperterm fulltime in order to be as productive as I'm with iTerm2.

**Comment by ieiayaobb** [comment]
Hope this can be supported then I can replace my iTerm2 totally

**Comment by chabou** [comment]
It will be great if a pane can temporarily take all the tab space. A sort of maximize into a tab.
Like Terminator on linux : http://gnometerminator.blogspot.fr/p/introduction.html

**Comment by mikekreeki** [comment]
@chabou iTerm does that too, I use it frequently. Would be great if Hyperterm supported that too.

**Comment by wjagodfrey** [comment]
The other iterm gives us is the ability to hide pane headers (see the grey bar over each pane in the screenshot above).

It also allows me to map key combos to move between panes relative to the current focus.

If we can get both of these features, that would be ideal.

**Comment by tleunen** [comment]
I also like the new way Atom did to create the split panes. You can grab a tab and drag/drop it in a specific area of the app to make it create the split panes the way you want.

**Comment by ekmartin** [comment]
There's an initial implementation available [here](https://github.com/zeit/hyperterm/pull/693) if you'd like to give it a try.

**Comment by mmathys** [comment]
@ekmartin ur fork is sick af

**Comment by c4milo** [comment]
great work on the split panes, beautifully done. I'm switching from iTerm now.

**Comment by kevinhowbrook** [comment]
Is this merged now? @rauchg

**Comment by tleunen** [comment]
Split panes are available since 0.8.1

**Comment by realogicbcleary** [comment]
Beautiful!  One issue tho: when my window manager (amethyst) shrinks Hyper, it seems like it doesn't redraw, so the lower pane gets hidden.  My work-around is to do a quick CMD+SH+D + CMD+W, but that hinges on remembering a pane just got hidden.

**Comment by maximeaubaret** [comment]
Nice, I was waiting for this :)

**Comment by ppot** [comment]
@realogicbcleary  Do an issue for that.

**Comment by michaelzoidl** [comment]
Is there a way to change to focused pane via a shortcut? E.g. in iTerm2 i can switch between them with `alt + cmd + <arrow-key>`

**Comment by ekmartin** [comment]
You can cycle back and forth with `Ctrl+Alt+Tab` and `Ctrl+Shift+Alt+Tab`. There's a couple of issues for other types of split key bindings here: #828 #1295

**Comment by mmathys** [comment]
@ekmartin martin, you the real mvp

**Comment by vnctaing** [comment]
You also can do it with `cmd+shift+[` or `cmd+shift+]` like on Atom

**Comment by dezman** [comment]
How can you expand a pane to full screen?

**Comment by ppot** [comment]
@dezman Can you be more specifc.

**Comment by dezman** [comment]
@ppot Im just wondering if there is a feature like cmd+shift+return in iTerm where the pane you are on fills the whole screen and you can toggle between viewing all your panes and expanding one to fill the screen. Thanks!

**Comment by ppot** [comment]
@dezman  Not at the moment! it's in the stack of things  to be implemented!

**Comment by dezman** [comment]
@ppot okay awesome, thanks for the info, is there a place i can check for the development of this feature?

**Comment by ppot** [comment]
@dezman This will be on the rebuild I am doing. You can open an issue for this at https://github.com/ppot/hyper/issues

**Comment by dezman** [comment]
@ppot great, thanks!

**Comment by itsashis4u** [comment]
Split pane command in linux/windows?

**Comment by iamstarkov** [comment]
@itsashis4u you can find it in the menu
![screen shot 2017-04-04 at 12 43 38](https://cloud.githubusercontent.com/assets/559321/24653023/61d8ffb2-1934-11e7-9c46-7289accc7ecb.png)

**Comment by itsashis4u** [comment]
Thanks, @iamstarkov.
I am using elementary os and I believe a global menu is not present in it. Will look for a workaround.

**Comment by mxmzb** [comment]
may i ask how you managed to greyscale out all the inactive panes?

**Comment by iamstarkov** [comment]
@mxmzb try this https://github.com/matheuss/hyper-simple-highlight-active-session

**Comment by Flaque** [comment]
Suggestion: move the "split" options to "View" instead of in "Shell".

**Comment by donatoaz** [comment]
Is there a shortcut to resize splits? In iTerm2 ctrl+cmd+arrows resizes the current splits. This way there is no need to use the mouse to drag in order to (in || de)crease the split.

Awesome terminal, loving it btw...
