### ISSUE TITLE
Backticks

### ISSUE THREAD

**Issue by akoenig** [zeit/hyperterm#568]
First of all, thanks for this wonderful piece of software :)

I encountered a problem with `backticks` while using HyperTerm on a daily basis. I'm not sure if this is due to the fact that the respective font does not contain this character or if it is due to some misconfiguration on my side. When I enter a backtick, HyperTerm just displays a `" "`. Can you enter backticks?

**Comment by chabou** [comment]
Are you using an international keyboard ?
0.7.1 or master branch ?
Do you enter backtick or backtick+space like with a french keyboard ?

Maybe duplicate #521

**Comment by akoenig** [comment]
I'm on a Mac using a german keyboard and trying to add backticks via `backtick + space`.

**Comment by chabou** [comment]
Ok so this issue is the same as #466 (which will be fixed by #214, I think)
