### ISSUE TITLE
Pressing ESC should clear selection

### ISSUE THREAD

**Issue by auchenberg** [zeit/hyperterm#591]
Pressing ESC should clear selection as in native `terminal` and `Iterm2`

**Steps to reproduce:**
- Open HyperTerm
- Press `CMD+A` to select everything
- Press `ESC`

**Expected:**
- Selection to cleared

**Actual:**
- Selection persisted.

**Comment by ppot** [comment]
In fact, the interpretation of Iterm2 and Terminal is to make a deselection of everything once the user type any keys or click again inside the current window.

**Comment by ppot** [comment]
@albinekb Could you take a look?
