### ISSUE TITLE
Tab switching with ⌘ + left arrow or ⌘ + right arrow not working

### ISSUE THREAD

**Issue by vbvyas** [zeit/hyperterm#592]
On El Capitan 10.11.6, HyperTerm 0.7.1 is not working for cmd (⌘) plus arrow keys (both left or right) to switch tabs. Although, ⌘ + # e.g. ⌘ + 1 is working to switch tabs.

**Comment by CodeTheory** [comment]
Removed intentionally in favour of `CMD + ALT + left/right arrow`. Hopefully configurable keybindings will be available in a future version. 😄
