### ISSUE TITLE
nano: Scrolling with the mouse wheel should scroll through the document

### ISSUE THREAD

**Issue by Shugabuga** [zeit/hyperterm#598]
Scrolling with the mouse wheel or the trackpad gesture should scroll through the opened file in `nano`.

**Comment by ekmartin** [comment]
Duplicate of https://github.com/zeit/hyperterm/issues/216

**Comment by Shugabuga** [comment]
Whoops! Sorry! 😞

**Comment by ekmartin** [comment]
No worries :)
