### ISSUE TITLE
Traffic lights should be centered

### ISSUE THREAD

**Issue by leo** [zeit/hyperterm#6]
How it looks:

![is](https://cloud.githubusercontent.com/assets/6170607/16539580/a8d0d686-4047-11e6-9d1a-1ccd50bb6728.png)

How it should look:

![should 2x](https://cloud.githubusercontent.com/assets/6170607/16539571/90b1739e-4047-11e6-8a49-b000f8c94656.png)

**Comment by rauchg** [comment]
I wish man. This kills me, but electron doesn't allow us to change it.

The alternative would be to re-create them from scratch. Maybe someone from the electron team can comment on what options we have. @zcbenz ?

**Comment by leo** [comment]
Making the tab bar slimmer would be an option. There [might](https://github.com/electron/electron/issues/6124) also be native tabs in the future.

**Comment by rauchg** [comment]
I don't love the native tabs :\

**Comment by leo** [comment]
@rauchg Wait a second! Can you try changing [this](https://github.com/zeit/hyperterm/blob/624b7c399299bd643c3f24b4c0de8b9b7a89c625/index.js#L38) to "hidden-inset"?

**Comment by leo** [comment]
Works fine (puts the traffic lights further away from the edge)! But we'll have to make the tabs a little bigger, if we want to do it this way. Otherwise, we'll have to use "hidden" and make the tabs smaller.

**Comment by rauchg** [comment]
How much taller would the tabs need to be?

**Comment by leo** [comment]
See https://github.com/zeit/hyperterm/pull/25

**Comment by katacarbix** [comment]
I know this is an old and closed issue, but have you seen (titlebar)[https://github.com/kapetan/titlebar]? (Here's a fork)[https://github.com/katacarbix/titlebar] that I made which adds support for Windows 10 style buttons. It allows custom styling for the buttons as well, so you can tweak it to any extent.
