### ISSUE TITLE
Run command on launch

### ISSUE THREAD

**Issue by Shugabuga** [zeit/hyperterm#600]
Is there a way to run a command (i.e. `echo Welcome to Terminal, Shugabuga!`) on start, or an way to do this with a plugin?

**Comment by matheuss** [comment]
The best way to achieve this is `echo Welcome to Terminal, Shugabuga!` in your `.bashrc|.zshrc|.bash_profile` ☺️

**Comment by Shugabuga** [comment]
Thanks! This worked!

But, let's say I made a plugin that runs a command when using a hotkey. Is there a programatic method of running commands in HyperTerm using Node.JS? If it's not possible, no biggie, just wondering for a (possible) future project.

**Comment by ppot** [comment]
@Shugabuga For better information you should link your plugin.  But for theoretical response you can use the NodeJS Child Process to either exec or spawn call to invoke bash request to your console.

**Comment by Shugabuga** [comment]
Yeah, the request was hypothetical. Just in case I wanted to do something like this in the future.

But thanks for your response! I'll do some research on that!
