### ISSUE TITLE
Hyperterm doesn't remember window position between restarts

### ISSUE THREAD

**Issue by booc0mtaco** [zeit/hyperterm#613]
I use [divvy](http://mizage.com/divvy/) to position windows on my mac. Usually, windows will remember their position after you quit and re-open the application. Hyperterm does not, however. It usually restarts at a smaller size, and centered on my secondary monitor. No settings are retained when the application quits (either manually or due to restart).

I suspect this may be an issue on all platforms, but have only seen it on my macOS system.

**Comment by CodeTheory** [comment]
Duplicate of #27
