### ISSUE TITLE
Drag and Drop of image open it in background

### ISSUE THREAD

**Issue by ppot** [zeit/hyperterm#616]
Drag and dropping of images seem to open them it the background instead of using there path.

**Comment by dj-hedgehog** [comment]
In version 0.7.1. there was no drag and drop behaviour implemented. The current `master` contains new behaviour that the path of dragged file will be added.

This issue can therefore be closed.

**Comment by ppot** [comment]
@dj-hedgehog Forgot I wasn't on local master but on HyperTerm 0.7.1
