### ISSUE TITLE
Repeated key presses don't register in Vim

### ISSUE THREAD

**Issue by jdsimcoe** [zeit/hyperterm#63]
If I press and hold a navigation key in vim like `h` or `j` the repeat doesn't register like it does in Terminal/iTerm.

**Comment by rauchg** [comment]
Using `0.3.1` ?

**Comment by jdsimcoe** [comment]
that was using `master` with the latest stuff

**Comment by jdsimcoe** [comment]
I'm testing it now and it is fine... Closing this @rauchg.

**Comment by Caryyon** [comment]
MacOS High Sierra 10.13.3 using Hyper 2.0.0-canary.14 with no plugins I am currently experiencing the same issue. I can't press and hold a key for a repeat.

**Comment by MAPESO** [comment]
@Caryyon Thanks for reporting this error🙏

**Comment by MAPESO** [comment]
@albinekb @chabou This error I thought it had been fixed in the canary version 🙍 😞

**Comment by MAPESO** [comment]
@chabou Thanks friend 😺

**Comment by Caryyon** [comment]
@jdsimcoe you could close this. There is a better spot for it as well as I found out that it was because of the little character popup that mac has. I disabled it and i can repeat now!

**Comment by adamki** [comment]
going off of @Caryyon ... i used this for mac OS
`defaults write -g ApplePressAndHoldEnabled -bool false`

**Comment by chovy** [comment]
thiw still doesnj't work.

**Comment by jdsimcoe** [comment]
@chovy Try doing this in Terminal or Hyper:

`defaults write co.zeit.hyper ApplePressAndHoldEnabled -bool false`

**Comment by jdsimcoe** [comment]
This same issue and workaround is referenced here: https://github.com/zeit/hyper/issues/2297#issuecomment-344265408.
