### ISSUE TITLE
Rendering issues (found with blessed.js)

### ISSUE THREAD

**Issue by jbergstroem** [zeit/hyperterm#639]
Had a run through `blessed.js` using the [dashboard example in blessed-contrib](https://github.com/yaronn/blessed-contrib). Results speak for themselves (iTerm left, hyperterm 125fdd98e5414b2cea99e8f7465720694c757386 right -- not saying that iTerm is doing a great job, but I think character widths seems to be a real issue for hyperterm) :

<img width="1440" alt="screen shot 2016-08-19 at 6 50 48 pm" src="https://cloud.githubusercontent.com/assets/176984/17825337/34711162-663e-11e6-8dc2-4925dd0cddf7.png">

Still getting acquainted to the development environment. Can hopefully aid in fixing bugs shortly.

**Comment by albinekb** [comment]
Duplicate of #46? (not sure)
Work in progress #535

**Comment by jbergstroem** [comment]
Looks like dup, yeah. Sorry!
