### ISSUE TITLE
Invalid US-ASCII character "\xC4" when compiling sass

### ISSUE THREAD

**Issue by DamianDzw** [zeit/hyperterm#643]
When working with my private project, compiling sass in hyperterm throws error

`error sass/apps/components/_upgrade_button.sass (Line 4: Invalid US-ASCII character "\xC4")`

when switching back to iTerm, everything compiles

**Comment by CodeTheory** [comment]
Hi there! Could you provide any more information on this error?

For example, it'd be useful to know what version of Sass you're running (version number and where it's from;  i.e node-sass, ruby sass gem etc.), the sass file that's causing the error and what version of HyperTerm you're running. 

I'll try and replicate the error to see if we can see the problem, although I can't see why HyperTerm would cause this currently!

**Comment by DamianDzw** [comment]
`sass --version` gives me Sass 3.4.22 (Selective Steve), i think is a sass gem
Hyperterm version 0.7.1

Error file have non english, Polish in this example comments, like this
`    // Do usunięcia lub modyfikacji w przyszłości`, 

But iTerm handles them with no problem

Im attaching a screenshot, left is Hyperterm, right is iTerm

<img width="859" alt="895cdea5f8372cef259602e574ec145a" src="https://cloud.githubusercontent.com/assets/9091672/17848477/0f272d7a-6854-11e6-8922-7af5f9c6e0e6.png">

**Comment by DamianDzw** [comment]
when using the command line, my locale was initially like this:

LANG="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_CTYPE="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_ALL=

I added the following to my ~/.bashrc file:

export LC_ALL=pl_PL.UTF-8
export LANG=pl_PL.UTF-8

And now it works.
