### ISSUE TITLE
Confirm before close tab if there is running process

### ISSUE THREAD

**Issue by delgermurun** [zeit/hyperterm#644]
It is nice to warn & ask/confirm before closing tab if there unfinished running process.

Is there way to do it now?

**Comment by CodeTheory** [comment]
I believe this is a duplicate. Please add any additional questions you have to #67.

If I've made a mistake closing this, feel free to re-open!

**Comment by delgermurun** [comment]
It is not exact duplication but I added comment on this issue. Thanks.
