### ISSUE TITLE
No warning when closing a tab with a running process

### ISSUE THREAD

**Issue by silverlight513** [zeit/hyperterm#649]
I was running a node server in one of the tabs I had open, I accidentally closed the tab and there was no warning asking me if I'm sure I want to close the tab and stop the process.

**Comment by CodeTheory** [comment]
I believe this is a duplicate. Please add any additional questions you have to #67.

If I've made a mistake closing this, feel free to re-open!

**Comment by silverlight513** [comment]
Yeah, one of the comments in that issue is asking for the same as me. Thanks :)
