### ISSUE TITLE
Cmd-K doesn't work while tailing

### ISSUE THREAD

**Issue by jesseditson** [zeit/hyperterm#65]
Saw cmd-k landed, and for most use cases it's working nicely. However, if I'm running a `tail -f` command, cmd-k no longer works. This is usually my primary use case for it - I clear the scrollback when tailing to "mark my place", then I can scroll to the top without getting confused with prior sessions.

**Comment by rauchg** [comment]
Yeah, it's buggy. I need to re-visit the algorithm.
