### ISSUE TITLE
No Emoji Support

### ISSUE THREAD

**Issue by heshamsalman** [zeit/hyperterm#655]
A lot of my commit messages include emoji. I like to think my team loves me for it. 

Edit: Some more information --

When attempting to access the emoji keyboard in OS X (ctrl-cmd-space), the picker appears away from the terminal. On selection of an emoji, no emoji is posted into the terminal. I've tried pasting an emoji from a text editor as well, to no avail.

**Comment by albinekb** [comment]
1. that's good, emojis are the future
2. duplicate https://github.com/zeit/hyperterm/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20emoji

**Comment by heshamsalman** [comment]
Video of issue:

[hyperterm_emoji.zip](https://github.com/zeit/hyperterm/files/437880/hyperterm_emoji.zip)

**Comment by andywer** [comment]
I think there is already a PR addressing this issue: #535

**Comment by matheuss** [comment]
See #66 😅
