### ISSUE TITLE
Config values aren't scoped

### ISSUE THREAD

**Issue by leo** [zeit/hyperterm#656]
This is how `config.store` using "electron-config" looks like:

```js
{ plugins: '{"plugins":["hypercwd","hyperterm-blink"],"localPlugins":[]}',
  'plugin-versions': '[["hypercwd","0.1.3"],["hyperterm-blink","1.1.0"]]',
```

As you can see, HyperTerm's configuration isn't scoped to hyperterm. We need to fix this!

So instead of doing the following:

```js
config.set('plugins', ...)
```

we need to do this:

```js
config.set('hyperterm.plugins', ...)
```

**Comment by BrianDGLS** [comment]
Hi @leo,

I have made the change that you specified above, see pr: [#669](https://github.com/zeit/hyperterm/pull/669).

Let me know if there is anything else involved, or if I have misunderstood the task.

Thanks,

Brian

**Comment by leo** [comment]
Fixed in https://github.com/zeit/hyperterm/pull/669
