### ISSUE TITLE
Tab title random changing

### ISSUE THREAD

**Issue by trevordmiller** [zeit/hyperterm#670]
![tabs-title-randomness](https://cloud.githubusercontent.com/assets/5497885/18039227/f737a794-6d5d-11e6-9f36-cdb74885ecb8.gif)

As shown in the gif above, the content in `.tabs_title` randomly cycles. For example, if I am inside of a bash shell, viewing git output with less, the tab title changes randomly between `bash`, `less` and `sh`. Another example: if I open a file in vim, the tab title changes randomly between `vim`, `bash`, and `Python`. The `Python` one is especially weird since I am not running any python. If HyperTerm could be patched to set the tab title to always reflect the current process (so in my case `less` and then when I quit less, go back to `bash` etc), that would be great :)

I don't have any plugins installed other than a color scheme; here is my `.hyperterm.js`:
```js
module.exports = {
  plugins: [
    'hyperterm-atom-dark',
  ],
  config: {
    padding: '17px',
    fontSize: 17,
    fontFamily: '"Fira Mono", monospace',
    cursorShape: 'BLOCK',
  },
};
```

# p.s.

I ❤️  HyperTerm! Thank you for your great work :)

**Comment by matheuss** [comment]
+1 for stopping this infinite loop 😛

**Comment by trevordmiller** [comment]
@matheuss Is this a bug instead of a feature request? I'm happy to submit a pull request to fix it if you can point me in the right direction - I haven't looked at the source code.

**Comment by chabou** [comment]
Duplicate #49

**Comment by matheuss** [comment]
I don't think it is a bug 😛 Closing in favor of #49 – thanks @chabou
