### ISSUE TITLE
"npm not in $PATH"

### ISSUE THREAD

**Issue by tyrollins** [zeit/hyperterm#672]
I keep getting a warning that npm is not in $PATH. I have node / npm installed via NVM could this be tripping it up? 

The npm command works fine when I navigate to .hyperterm_plugins and do `npm install`, it all plugins just fine, however I continue to receive a warning that 'npm is not in path'

Am I missing something?  

Current $PATH - 
`/usr/local/sbin:/Users/username/.rbenv/shims:/Users/username/.nvm/versions/node/v6.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

**Comment by matheuss** [comment]
Duplicate – #443
