### ISSUE TITLE
now --help renders '<zeit icon> no' instead of '<zeit icon> now'

### ISSUE THREAD

**Issue by timneutkens** [zeit/hyperterm#673]
Asked @leo about it. He said the now code is ok and that it's most likely a hyperterm issue.
Might be related to pull request #535 
<img width="1552" alt="screen shot 2016-08-29 at 20 02 33" src="https://cloud.githubusercontent.com/assets/6324199/18061614/a6b7a7d0-6e23-11e6-82f8-686148d2cc03.png">

**Comment by matheuss** [comment]
I think this is a duplicate 😅 This also happens with emojis and composed chars 😛

**Comment by timneutkens** [comment]
Hehe I though so @CodeTheory please close it if it's a dupe 😉

**Comment by matheuss** [comment]
I'll bump #535 😋
