### ISSUE TITLE
Running cat on a PDF results in garbled characters

### ISSUE THREAD

**Issue by marcus-crane** [zeit/hyperterm#677]
Running `cat` on some PDFs results in characters being garbled until Hyperterm is restarted. Definitely not high priority but still interesting anyway.

![hyperterm_bug](https://cloud.githubusercontent.com/assets/14816406/18112396/570bdacc-6f7b-11e6-92ba-20196145ff85.png)

The characters are valid in that you can still type commands and run them so it's purely a visual issue.

I'm going to assume this is related to Hyperterm and not `cat` itself since I don't have any other terminals to test at the moment. I haven't had the same issue with the regular OS X terminal

**Comment by cjb** [comment]
Same issue with any terminal. It's an ANSI escape sequence that switches to a graphics mode.  `reset` fixes it.

**Comment by marcus-crane** [comment]
Oooh, that's actually really interesting! I'll have to have a look into that actually.

**Comment by albinekb** [comment]
Why would you `cat` a pdf? 💭

**Comment by marcus-crane** [comment]
Why wouldn't you!

Haha, I was bored on the train this morning (with no WiFi) and I just started using `cat` on my Documents folder. Y'know, stuff that it isn't intended to be used on just to see what would happen. 

I didn't realise it was an ANSI thing though since the regular OSX Terminal didn't give me the same issue.
