### ISSUE TITLE
Fonts are broken?

### ISSUE THREAD

**Issue by rumpelsepp** [zeit/hyperterm#681]
HyperTerm htop vs Termite htop (see the dotted graph). Let me know which information you need.

HyperTerm
![2016-09-01-100541_1079x251_scrot](https://cloud.githubusercontent.com/assets/1961699/18160076/e5b824d2-702b-11e6-82e7-14059ce047e0.png)

Termite
![2016-09-01-100559_943x185_scrot](https://cloud.githubusercontent.com/assets/1961699/18160042/c26879aa-702b-11e6-8dda-dc95afd7422c.png)

The font is Liberation Mono in both screens.

**Comment by matheuss** [comment]
Duplicate 😅 #46

**Comment by rumpelsepp** [comment]
ah. thx. :)
