### ISSUE TITLE
Weird Dark boxes around text

### ISSUE THREAD

**Issue by chobot2014** [zeit/hyperterm#694]
So, I don't really know what's going on, but I'm kind of salted because I got this terminal and fell in love, like great work, all around. being somebody who loves material design on things, i searched for a material design theme for this, and lo and behold, I saw one that looked fan-freakin-tastic. I followed the instructions and was saddened to find it not work like it said on the picture.. https://www.npmjs.com/package/hyperterm-material

This is what it looks like:

<img width="50%" alt="screen shot 2016-09-06 at 1 19 35 am" src="https://cloud.githubusercontent.com/assets/14955162/18263486/ff54c592-73cf-11e6-84d9-858175eec093.png">

With tmux: 
<img width="50%" alt="screen shot 2016-09-06 at 1 22 48 am" src="https://cloud.githubusercontent.com/assets/14955162/18263539/76c5624e-73d0-11e6-9ddf-cd76aa725b32.png">

I mean, it's not the end of the world, but it would be awesome to see how I could fix it! Have a great day!

**Comment by chabou** [comment]
Maybe it is better to post this issue on hyperterm-material repository ? https://github.com/dperrera/hyperterm-material

Compatibility issue with recent version of hyperterm ?

**Comment by matheuss** [comment]
I can't reproduce it 😨 
![screen shot 2016-09-06 at 10 36 57 am](https://cloud.githubusercontent.com/assets/4721750/18275551/d9cb1ae4-741d-11e6-9025-4152bd1c706a.png)

Have you tried a `cmd + shift + R`?

**Comment by chobot2014** [comment]
Sadface.jpeg. 
UPDATE: 
Visual studio code has same issue? Probably shouldn't be on this thread anymore, but if you could help, I would extremely appreciate it. It was fine yesterday (vscode)
<img width="1217" alt="screen shot 2016-09-06 at 8 46 29 am" src="https://cloud.githubusercontent.com/assets/14955162/18275891/85bc2f6a-740e-11e6-97cc-f9ca24f34ef0.png">

**Comment by matheuss** [comment]
WTF 😱 I would try restarting macOS 😰

**Comment by chobot2014** [comment]
I stayed up most of the night trying to fix this, and I think it's worth it to wipe macOS and restart just to get this terminal working as intended. Beautiful software guys. <3

**Comment by matheuss** [comment]
Feel free to reopen if needed!! 😄
