### ISSUE TITLE
Centralized Extensions Repository?

### ISSUE THREAD

**Issue by Miserlou** [zeit/hyperterm#700]
There's a lot of documentation about writing extensions, and I certainly like this as a platform and plan on writing my own extensions, but where can I see what's already been written? It doesn't look like there is a good centralized repository of all of the good extensions. This seems like an important piece of critical infrastructure for this project.

**Comment by leo** [comment]
Like most node.js projects, we're using npm to [host our plugins](https://npms.io/search?term=hyperterm-).

**Comment by Miserlou** [comment]
Not for hosting, for browsing. Which are approved? How am I supposed to tell what's worth installing, etc? Reviews, descriptions, etc.

**Comment by iamstarkov** [comment]
check https://github.com/bnb/awesome-hyper list
