### ISSUE TITLE
Prompt gets mis-aligned when PS1 includes emoji 😥

### ISSUE THREAD

**Issue by plmrry** [zeit/hyperterm#704]
We all know how important it is to have emoji in our bash prompt.

Adding emoji moves the prompt down and it gets cut off when at the bottom of the window.

![screen shot 2016-09-10 at 2 12 41 pm](https://cloud.githubusercontent.com/assets/688617/18412788/b3e0a39e-7765-11e6-9cb9-17953bb877c0.png)
![screen shot 2016-09-10 at 2 13 37 pm](https://cloud.githubusercontent.com/assets/688617/18412787/b3df2d34-7765-11e6-9ce3-518749b01ecd.png)

😢

**Comment by matheuss** [comment]
#154 🙂
