### ISSUE TITLE
Question mark characters

### ISSUE THREAD

**Issue by trevordmiller** [zeit/hyperterm#708]
When switching panes in Tmux, I get question mark characters in the corner of the pane that change with each switch. I'm using default Tmux settings which have worked on all other terminal emulators I've used; I cannot reproduce in iTerm2 so this seems to be something related to HyperTerm.

![image](https://cloud.githubusercontent.com/assets/5497885/18520483/40c1e578-7a65-11e6-9276-b2756f8f62c4.png)

![tmux-question-marks](https://cloud.githubusercontent.com/assets/5497885/18520430/0a7ccb90-7a65-11e6-8740-abc8f2db5e2d.gif)

**Comment by matheuss** [comment]
#139 😅

**Comment by trevordmiller** [comment]
I'm sorry for the duplicate. I tried searching beforehand and didn't see that one. Thank you.

**Comment by matheuss** [comment]
No problem 🙌
