### ISSUE TITLE
Feature Request: GUI for command history

### ISSUE THREAD

**Issue by aleclarson** [zeit/hyperterm#710]
It would be nice to view a list of my command history (and easily scroll then click a command to reuse it).

**Comment by leo** [comment]
Just use the up and down keys to cycle through the history. 😊

**Comment by aleclarson** [comment]
@leo Yup, I know that's there.

At the minimum, Hyperterm should expose a command for getting a specific index in the history. I despise hitting the up key like a maniac whenever looking for a command further back in the history.

What do you think?

**Comment by flybayer** [comment]
@aleclarson I **highly** reccommend checking out https://github.com/junegunn/fzf. It's a command line fuzzy finder. 

With it, you can hit `Ctrl-R` from your terminal and get a fuzzy search window of all your previously issued commands :ok_hand: 

![image](https://cloud.githubusercontent.com/assets/8813276/18553757/474f660a-7b27-11e6-9c25-c00a636aca3d.png)

You can also set up things like a `vimf` command that will launch the fuzzy finder for opening a file in vim.

**Comment by aleclarson** [comment]
@flybayer Thanks for the help! 👍  Do you know if it would work in something like the NodeJS repl?

**Comment by matheuss** [comment]
> At the minimum, Hyperterm should expose a GUI for copying a command
(from the history) using a specific index.

![screen shot 2016-09-15 at 1 54 34 pm](https://cloud.githubusercontent.com/assets/4721750/18559060/f4e37d78-7b4b-11e6-9f06-23f7228a3223.png)
😄

**Comment by c0b41** [comment]
I would recommend   [peco](https://github.com/peco/peco)

**Comment by flybayer** [comment]
@aleclarson I doubt it works with the node REPL out of the box, but it could probably be configured to work with it.
