### ISSUE TITLE
UI switched to system "header bar" macOS

### ISSUE THREAD

**Issue by nkubiez** [zeit/hyperterm#711]
The issue I'm addressing is the gray bar at the top of the window. I've attempted to delete and reinstall or remove plugins multiple times but each time it installs I have the same issue and it remembers my themes, plugins, etc. How can I get rid of the bar? Am I missing some type of preference file somewhere that holds this data?

Issue on macOS v10.11.6 El Capitan w/ Hyperterm v0.7.1.36

<img width="551" alt="screen shot 2016-09-14 at 10 07 36 pm" src="https://cloud.githubusercontent.com/assets/10440648/18536138/67aea6cc-7ac8-11e6-93ea-41b5e4b22598.png">

**Comment by flybayer** [comment]
Did you try deleting `~/.hyperterm.js` (or renaming it so you have a backup)? If that file is missing, Hyperterm will generate a fresh one for you.

**Comment by nkubiez** [comment]
Yep thanks worked well!
