### ISSUE TITLE
Help >> about

### ISSUE THREAD

**Issue by micrub** [zeit/hyperterm#718]
Seems that it shows same version all the time when npm started from master.

**Comment by matheuss** [comment]
I don't get it... What are you talking about? 😰

**Comment by flybayer** [comment]
I've noticed this too. The About dialog always shows the latest git tag (such as 0.7.1) even though it's built from 0.7.1 + 100 commits. Ideally, the about menu would show the version as `0.7.1-<git_hash>` just like you'd get from `git describe`.

**Comment by matheuss** [comment]
Oh, now I get it 😄 Thanks for the clarification @flybayer 😄
