### ISSUE TITLE
`npm install` fails on `postinstall`

### ISSUE THREAD

**Issue by atdrago** [zeit/hyperterm#722]
Hyperterm `npm install` fails on `postinstall`. I followed instructions on the README. Any idea what I'm doing wrong?

> hyperterm@1.0.0 postinstall /Users/adamdrago/Documents/git/hyperterm
> install-app-deps

> Error: install-app-deps is only useful for two package.json structure
>     at /Users/adamdrago/Documents/git/hyperterm/node_modules/electron-builder/src/install-app-deps.ts:31:4
>     at next (native)
>     at runCallback (timers.js:574:20)
>     at tryOnImmediate (timers.js:554:5)
>     at processImmediate [as _immediateCallback] (timers.js:533:5)
> From previous event:
>     at tsAwaiter (/Users/adamdrago/Documents/git/hyperterm/node_modules/electron-builder/src/util/awaiter.ts:10:47)
>     at main (/Users/adamdrago/Documents/git/hyperterm/node_modules/electron-builder/src/install-app-deps.ts:23:3)
>     at Object.<anonymous> (/Users/adamdrago/Documents/git/hyperterm/node_modules/electron-builder/src/install-app-deps.ts:37:28)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.runMain (module.js:590:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
> 
> npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-linux:
> npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-linux@1.0.2
> npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-win:
> npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-win@2.0.1
> npm ERR! Darwin 15.6.0
> npm ERR! argv "/Users/adamdrago/.nvm/versions/node/v6.6.0/bin/node" "/Users/adamdrago/.nvm/versions/node/v6.6.0/bin/npm" "i"
> npm ERR! node v6.6.0
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! hyperterm@1.0.0 postinstall: `install-app-deps`
> npm ERR! Exit status 255
> npm ERR! 
> npm ERR! Failed at the hyperterm@1.0.0 postinstall script 'install-app-deps'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the hyperterm package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     install-app-deps
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs hyperterm
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls hyperterm
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/adamdrago/Documents/git/hyperterm/npm-debug.log

**Comment by matheuss** [comment]
This is not supposed to happen since we have 2 `package.json` 🤔

Can you confirm that you have one in the root of the repo and one in the `app` folder?

**Comment by atdrago** [comment]
I don't have an `app` folder.

**Comment by matheuss** [comment]
😨! So you might want to clone the repository again since we have one [`app`](https://github.com/zeit/hyperterm/tree/master/app) folder 😅

**Comment by atdrago** [comment]
Wow.. sorry.. lol
