### ISSUE TITLE
Is this open source? Where is the license?

### ISSUE THREAD

**Issue by Flimm** [zeit/hyperterm#73]
It's not clear to me if this is meant to be open source or not. What license is it under?

This is a useful website by the GitHub team that helps you choose a license if you haven't already: http://choosealicense.com/

**Comment by rauchg** [comment]
@Flimm it's not clear yet because the website is not public 😅. The license is MIT.

**Comment by rauchg** [comment]
Thanks for the http://choosealicense.com/ pro-tip, didn't know about it.
