### ISSUE TITLE
Windows and Linux

### ISSUE THREAD

**Issue by SteveWinfield** [zeit/hyperterm#742]
I was wondering if there is any information regarding **Windows and Linux support**. The web page says **"Builds for Windows and Linux are coming very soon!"** even though there is already an "AppImage" Linux build available. What's left to do in order to call it stable?

Cheers!

**Comment by CodeTheory** [comment]
Support for Windows is addressed within #167 and there are quite a few issues that are still open regarding Linux support. I believe that there are still some issues regarding compatibility with some Linux builds but I'm really not sure where the progress is at with that.

If you find any Linux issues that are still open but seem to be resolved, please comment and we could get a better idea of where progress is at. 😄

**Comment by SteveWinfield** [comment]
The only bug that I noticed on Linux - I've used HyperTerm on Linux for less than two days - is mentioned in #127. I'd like to work on it, but I'm not in possession of a macOS machine. Therefore, I'm unable to test my changes on the only (officially) supported platform.

**Comment by CodeTheory** [comment]
I think an active user of HyperTerm on linux is @flybayer. Perhaps he could fill us in on how it acts and if we could possibly list the app as _for_ Linux yet.
