### ISSUE TITLE
New theme

### ISSUE THREAD

**Issue by christoga** [zeit/hyperterm#751]
Will you guys create another theme in the future? Or you guys will only use the black one?

**Comment by matheuss** [comment]
@christoga https://github.com/bnb/awesome-hyperterm#themes 🔥

**Comment by CodeTheory** [comment]
I think you're talking about the default theme, right? There's no plans to change it at all.

**Comment by christoga** [comment]
No mate, what I was trying to say is:
"Will the default theme be the only theme that is available to use?"

That's why I'm trying to say mate.

**Comment by matheuss** [comment]
Well, the default theme is not the only theme that is available to use 😛 There's a lot of them on npm 😄

**Comment by CodeTheory** [comment]
Recommended to use HPM though. https://github.com/zeit/hpm
