### ISSUE TITLE
When opening a new tab, default to same directory as previous tab

### ISSUE THREAD

**Issue by lcrossan** [zeit/hyperterm#753]
When I'm developing, I tend to be deep in some filesystem somewhere touching a specific directory, and I often want to open a new tab and do some work there, maybe while a long install or similar runs in the previous tab. But when you open a new tab it always dumps you out at `~/`.

Currently, there's no config option (afaik) to change this -- I'd like either a configuration option for it or more hooks in the Extensions API for tab info. The main things I'd need to make an extension for this are:

* Ability to get the index of tabs, including a current one
* An event hook similar to `onWindow` for tab creation
* Ability to get the current directory of a specific tab

This is the only thing keeping me from switching full-time to Hyperterm from iTerm2. I don't mind doing the work to build the extension either.

Thanks!

**Comment by CodeTheory** [comment]
There's a plugin for this already 😄 https://www.npmjs.com/package/hypercwd

**Comment by lcrossan** [comment]
Kick ass. Thanks!
