### ISSUE TITLE
How vulnerable is hyperterm to stuff like XSS attacks?

### ISSUE THREAD

**Issue by beane** [zeit/hyperterm#77]
I don't know too much about web security, but wouldn't exposing your terminal to normal browser traffic make attacks a lot scarier? Like instead of just hijacking a web session, maybe a determined attacker could get more direct access to your OS?

Would love to hear some discussion on the topic.

(Aside from that, the project is super cool!)

**Comment by rauchg** [comment]
`<webview>` is completely sandboxed by default. It's basically a "cool iframe". I should probably clarify this in an FAQ!
