### ISSUE TITLE
uncaught exception when closing window (without quitting the app)

### ISSUE THREAD

**Issue by nfcampos** [zeit/hyperterm#78]
(on master as of right now)

<img width="532" alt="screen shot 2016-07-08 at 16 18 58" src="https://cloud.githubusercontent.com/assets/56902/16692260/ec91204e-4527-11e6-99cc-d5f19e0d085a.png">

**Comment by rauchg** [comment]
Can you retry against most current master ?

**Comment by nfcampos** [comment]
yes, still happens. This only happens when closing the last tab with either in the menu Shell > Close or with its shortcut cmd+w. If the window is closed with the traffic lights this doesn't happen

**Comment by ppot** [comment]
@nfcampos Do you still have this problem? Seam to be working now.

**Comment by nfcampos** [comment]
I can confirm this is no longer an issue on v0.7.1
