### ISSUE TITLE
Extend README.md

### ISSUE THREAD

**Issue by leo** [zeit/hyperterm#8]
A few things we need in there:

- [x] What is hyperterm? Why does it exist? Why is it special? (aka. "Description")
- [x] Screenshot or GIF showing usage
- [x] How to contribute

I also think that we should convert all "TODO" items into issues (makes them easier to manage and discuss about with the community).

**Comment by rauchg** [comment]
The description and gifs are also missing from https://github.com/zeit/hyperterm-website

**Comment by ericclemmons** [comment]
I was wondering what hyperterm was for myself :) Dunno if it's an alternative to https://github.com/shockone/black-screen or something else entirely.

**Comment by matiastucci** [comment]
Also, you can add the url to the repo 🙂

<img width="364" alt="screen shot 2016-07-07 at 4 46 24 am" src="https://cloud.githubusercontent.com/assets/3856355/16641115/d29ce900-43fd-11e6-88dd-e31b3adafe33.png">
