### ISSUE TITLE
Can't specify border-color of active tab

### ISSUE THREAD

**Issue by zpao** [zeit/hyperterm#93]
The active tab `li` has an inline style `border-color: #333 !important` making it impossible to override in any way. For most other properties you can target `.t_active`.

Note: you also can't change `color`. It's a related but probably technically distinct issue (that's in what appears to be a generated stylesheet with a generated class name - `.t_active.active_1gcgehd` - targetable but looks fragile). Unless there's a complete effort on styling tabs, you may want to decouple these 2 things.

**Comment by albinekb** [comment]
Now the inline-style is not set with `!important` anymore, making it possible to override with 
```li.tab_active { border-color: red !important; }``` 

The same goes for color, @zpao can you check if this works as expected for you? 

Thanks

**Comment by leo** [comment]
It does!
