### ISSUE TITLE
Can't open http://localhost:3000

### ISSUE THREAD

**Issue by langolf** [zeit/hyperterm#98]
It seems we cannot open url without domain zone. But I really need :)

Also hyperterm crashes when I try add `.com` in the end
`http://localhost:3000.com`

**Comment by kinduff** [comment]
👍 Able to reproduce. Unable to open localhost y crashes with dot com at the end.

**Comment by kinduff** [comment]
This is a duplicate of #97, the `.com` at the end should be also fixed, not sure if that bug is part of the same issue.

**Comment by iamstarkov** [comment]
just ran `open http://localhost:3000` and that works perfectly fine

**Comment by langolf** [comment]
@iamstarkov We are talking about opening inside hyperterm as normal urls. Hyperterm already can do this with normal urls.

**Comment by iamstarkov** [comment]
@langolf what do you mean?

**Comment by langolf** [comment]
@iamstarkov you can open any url inside hyperterm window like a browser
https://monosnap.com/file/jzAKLD1oI3wPAi5U3Go7r17HivvOTk

**Comment by iamstarkov** [comment]
how did you do this?

**Comment by langolf** [comment]
@iamstarkov just type `http://someurl` or `www.someurl` in shell

**Comment by iamstarkov** [comment]
thats neat, how do use it?

**Comment by langolf** [comment]
I use vim for development. So it's very convenient to have "browser" in next-tab. E.g. I don't need to cmd-tab to browser to check markup.

**Comment by kopollo** [comment]
try from here [http://localhost.support/:3000](http://localhost.support/:3000)
